- src/jupyterlabcontroller/models/tag.py
- tests/tag_test.py
Import the tag parsing tests from cachemachine. There were almost no tests of the tag parsing logic and this (for now until we create a shared model library) will be the canonical location for this code, so import the tests from cachemachine and reformat them a little to be less verbose. Anticipate eventually moving the tag out of models to its own abstract data type in the naming of the test suite.
Refactor the construction of the build component in tags to fix a bug I noticed (`|` were left behind in the build component) and make the code a bit easier to follow.
> DM-37933: Better testing of tag parsing

- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/models/domain/docker.py
- src/jupyterlabcontroller/models/v1/prepuller_config.py
- src/jupyterlabcontroller/storage/docker.py
- tests/conftest.py
- tests/storage/docker_test.py
- tests/support/docker.py
Rather than using separate credentials for the Docker storage layer test, plumb through the dynamic loading of credentials and use the default credentials for the test configuration, along with the default registry and repository. This enables creating the Docker storage object via the factory, so provide a test factory as a fixture and add a method to create a Docker storage object.
Simplify the DockerCredentials class to stop storing username and password in two different forms and instead derive the other forms from username and password.
This work uncovered a latent minor bug in the Docker storage layer, where a spurious extra slash was added to the URL for getting tag and image information. The Docker API apparently swallows this but respx doesn't, so redo the repository and path …
> DM-37933: Simplify and further test Docker credential handling

- src/jupyterlabcontroller/config.py
- src/jupyterlabcontroller/constants.py
- src/jupyterlabcontroller/dependencies/config.py
- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/main.py
- src/jupyterlabcontroller/models/domain/docker.py
- src/jupyterlabcontroller/services/prepuller/docker.py
- src/jupyterlabcontroller/services/prepuller/executor.py
- src/jupyterlabcontroller/storage/docker.py
- src/jupyterlabcontroller/storage/gafaelfawr.py
- tests/configs/standard/input/config.yaml
- tests/conftest.py
- tests/storage/docker_test.py
- tests/support/mockdocker.py
The runtime section of the `Configuration` object had various parameters that were determined during configuration load and then set after creating the object, which required awkward initialization that was then ignored. All of these parameters could be handled a different way:
- `instance_url` was really `base_url` and needed to be initialized from an environment variable, which allowed it to be a normal top-level configuration parameter as long as the top-level configuration was changed to inherit from `BaseSettings` so that it would check the environment.
- `namespace_prefix` could be initialized from a `default_factory` function and was therefore moved to the lab configuration, since that's where it's used. (It's also reused as the namespace for prepulling, but shouldn't be; this will …
> DM-37933: Config and Docker credentials refactor

- src/jupyterlabcontroller/models/domain/rsptag.py
- tests/models/domain/rsptag_test.py
On Telescope and Site deployments where it is vital to prevent spawning images from the wrong SAL cycle, alias tags like recommended also have a cycle appended. Recognize those tags sufficiently to capture the cycle so that they're not excluded by cycle filtering when constructing the image menu.
> DM-37933: Recognize unknown tags with a cycle

- src/jupyterlabcontroller/models/domain/rsptag.py
- tests/models/domain/rsptag_test.py
Add a new class method to create alias tags. Do a bit of parsing of the tag name to extract a cycle if present, ensuring that the tags won't be filtered out by a cycle restriction (and making the display name a bit nicer because we can).
This constructor will be used in an upcoming change.
> DM-37933: Add RSPImageTag constructor for alias tags

- src/jupyterlabcontroller/main.py
- tests/conftest.py
Ensure all tests run with a mocked Kubernetes API. This is not currently used, since we currently also mock the Kubernetes storage object, but it ensures that initialize_kubernetes doesn't fail if there is no Kubernetes configuration. This allows removal of a workaround in create_app.
Move the startup and shutdown handlers into create_app to make it more explicit that they're private to create_app. Update the docstring with the true reason why we're deferring app creation: we want to give the test suite a chance to replace the configuration first.
> DM-37933: Simplify create_app

- src/jupyterlabcontroller/models/domain/rsptag.py
- tests/models/domain/rsptag_test.py
semver ignores the build component of the version when comparing versions, but that's where we put the cycle and cycle build information. We therefore don't want to ignore it because we want tags with a newer cycle or cycle build to sort after ones with an older cycle or cycle build for otherwise identical versions, and tags with a cycle to sort after ones without a cycle. This ensures that when presenting tags in reverse sorted order, ones with a newer cycle or cycle build will be shown first.
> DM-37933: Include build information when sorting tags

- src/jupyterlabcontroller/models/domain/rspimage.py
- tests/models/domain/rspimage_test.py
Continuing to lay the groundwork for a clearer expression of the complex image analysis algorithm, this introduces abstract data types for tracking images. An image is a tag annotated with its registry, repository, and digest, and is used to drive prepulling and to compare against when determining what images are cached.
As with RSPImageTagCollection, the operations on RSPImageCollection are chosen to satisfy the requirements of subsequent changes. This is where nearly all logic for alias handling, including resolving aliases to their underlying tags, is done.
> DM-37933: Add RSPImage abstract type and its collection

- src/jupyterlabcontroller/exceptions.py
- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/models/domain/docker.py
- src/jupyterlabcontroller/models/domain/kubernetes.py
- src/jupyterlabcontroller/models/domain/rsptag.py
- src/jupyterlabcontroller/models/v1/lab.py
- src/jupyterlabcontroller/services/image.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/storage/docker.py
- tests/configs/standard/input/test_objects.json
- tests/configs/standard/output/env.json
- tests/handlers/user_status_test.py
- tests/services/lab_test.py
The decision to not retrieve digests for all available images means that labs spawned from the dropdown menu may not have digests. However, we always want to record the digest of the image when spawning the pod for debugging purposes and better user display. The lab service also had some left-over reference and tag parsing code to reconstruct information about the image from the reference passed in via the lab creation form.
Correct this by adding a new method to the image service to create an RSPImage from a Docker reference, and then use the RSPImage as the source of data to encode in the pod environment ConfigMap. In the process, change image to reference in the lab options model and refactor reference parsing so that it can be shared between the lab service and cached image analysis.
> DM-37933: Ensure all labs are spawned with a digest

- src/jupyterlabcontroller/dependencies/context.py
- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/storage/k8s.py
- tests/conftest.py
- tests/handlers/user_status_test.py
- tests/services/lab_test.py
- tests/settings.py
- tests/support/kubernetes.py
Stop using the mock Kubernetes storage object in favor of a full mock of the Kubernetes API for the methods that the lab controller calls. This is temporarily implemented as a subclass of the mock class provided by Safir, but those changes will be rolled back into Safir once they have been thoroughly exercised.
This uncovered a timing problem with one lab service API test, where deletion was handled by a background task and therefore the user map didn't update immediately. Handle that with a delay that should be more than long enough for the background deletion to clean things up.
Remove some code from the Kubernetes storage layer that is handled by the Watch API. Setting _preload_content isn't an optimization; it tells the API to return the raw HTTP response rather than the deserialized …
> DM-37933: Switch to full Kubernetes API mocking

- src/jupyterlabcontroller/constants.py
- src/jupyterlabcontroller/exceptions.py
- src/jupyterlabcontroller/handlers/labs.py
- src/jupyterlabcontroller/models/v1/lab.py
- src/jupyterlabcontroller/services/image.py
- src/jupyterlabcontroller/services/lab.py
- tests/configs/standard/input/test_objects.json
- tests/handlers/user_status_test.py
- tests/services/lab_test.py
Implement the alternate interface to the /create route that allows services to select their image by ignoring the JupyterHub form and instead POSTing known values for image_tag or image_class, allowing them to bypass an API request to the lab controller to get the correct image reference to use.
Collapse the models for lab options into a single model and use validators to convert from the wire format resulting from the JupyterHub form post. This enlists Pydantic to do all the cleanup and validation for us and generate the correct 422 responses if needed, which simplifies the error handling and makes the models less complex and more consistent.
Update the username and group regexes from Gafaelfawr.
> DM-37933: Support bot user interface to lab creation

- src/jupyterlabcontroller/models/v1/lab.py
- tests/models/v1/lab_test.py
Treat empty lists in UserOptions input equivalent to None. Add a test for UserOptions to ensure that DROPDOWN_SENTINEL_VALUE is handled correctly, lists are converted to regular elements, and booleans are converted correctly.
If both image_list and image_dropdown are set (but only those two), use image_list and ignore image_dropdown. Due to how our form is designed, image_dropdown will always be set, but if image_list is not the sentinel value, it should override.
Stop configuring UserOptions with use_enum_values. This was an attempt to put strings into the dict() output for easier testing, but the test suite has been refactored to not need this, and this put the string directly into the model attribute as well, breaking other parts of the code.
> DM-38279: Fix handling of image selection in lab UserOptions

- src/jupyterlabcontroller/models/v1/lab.py
- src/jupyterlabcontroller/services/lab.py
- tests/handlers/user_status_test.py
Gafaelfawr now optionally includes quota information for the Notebook Aspect of the Science Platform if it is configured to track user quotas. Get the quota information for the namespace quota from there instead of from JupyterHub, which will never know what quota to use in the nublado design.
> DM-37833: Get notebook quota information from Gafaelfawr

- src/jupyterlabcontroller/services/lab.py
- Fix ordering of sizes in the menu
- Return the expected internal URL of the lab in response to start, since the start method of the spawner needs it
> Fix internal_url and ordering of sizes (again)

- src/jupyterlabcontroller/handlers/labs.py
- src/jupyterlabcontroller/services/lab.py
- tests/services/lab_test.py
If we wait for namespace deletion in the background and return immediately to JupyterHub, JupyterHub assumes that we have deleted the lab and may immediately attempt to create a new one, which then fails.
> DM-38279: Wait for lab deletion before returning

- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/services/size.py
- src/jupyterlabcontroller/storage/k8s.py
- tests/configs/standard/output/pod.json
- tests/handlers/user_status_test.py
- tests/services/lab_test.py
- tests/services/size_test.py
When I added support for Gafaelfawr quota settings, it broke pod spawning because I missed some pieces. Set resource requests and quotas on the pod based on the size of pod requested by the user, and set the same requests and limits for the init container (even though it probably won't need nearly as much) since that preserves the same total pod requirements and is easy.
Refactor the size manager to use methods rather than properties that do a lot of work, and to return the resources for a specific lab size, which is a bit more convenient elsewhere in the code.
> DM-38279: Fix quota handling

- src/jupyterlabcontroller/services/lab.py
Send the new progress percentage before the message, since the REST spawner class needs the new progress percentage when it emits the message.
> DM-38279: Change order of progress messages

- src/jupyterlabcontroller/handlers/labs.py
- tests/handlers/user_status_test.py
The URL to which we redirected the lab creation response is protected by different authentication rules and would require a different token. This probably indicates a deeper problem that we should rethink, but since the REST spawner doesn't want to follow the redirect anyway, return 201 with an empty body and a Location header instead.
> DM-38279: Return 201 from lab create route

- src/jupyterlabcontroller/storage/k8s.py
The standard Argo CD labels for the pod weren't present because they were overwritten by the extra label we wanted to add. Update the dict instead of overwriting it.
> DM-38279: Don't overwrite pod labels

- src/jupyterlabcontroller/constants.py
- src/jupyterlabcontroller/models/v1/lab.py
The validator was deleting image_list entirely when image_dropdown was set, but we later need to check whether it is None. Set it to None in this case instead.
> DM-38279: Fix handling of image_dropdown

- src/jupyterlabcontroller/handlers/labs.py
If someone asks us for events for a user that we've never heard of, we'll just block forever unless someone happens to create a lab for that user. Instead, return 404 if we've never heard of the user. Labs should always be created before asking for their events, and if the lab doesn't exist, the events shouldn't either.
> DM-38279: Don't return an event stream for nonexistent users

- Dockerfile
- scripts/start.sh
Follow the pattern from Gafaelfawr, even though our start command is fairly simple. Add the --factory flag, which uvicorn warns is missing when not provided.
> DM-38279: Use a start script to start the application

- src/jupyterlabcontroller/services/image.py
- tests/conftest.py
- tests/services/lab_test.py
We don't want to start answering user requests until we've populated our list of available images, since otherwise the spawner form may be bogus. Implement this by not returning from start until the first update pass is complete.
Don't start background services by default when using a test factory and update the tests that use it to start the background services themselves.
> DM-38279: Wait for first image service run during startup

- src/jupyterlabcontroller/factory.py
The Factory object was unconditionally stopping background services when closed, but we don't always start them now. This produced spurious warning messages when looking at the logs from tests. Only stop the background services if we started them.
> DM-38279: Only stop background services if started

- src/jupyterlabcontroller/storage/k8s.py
- tests/configs/standard/output/lab-objects.json
- tests/support/kubernetes.py
Modify the Kubernetes mock to add the created namespace to its objects so that we can check it has the right annotations.
> DM-38279: Also check the created namespace

- src/jupyterlabcontroller/models/domain/rspimage.py
- tests/models/domain/rspimage_test.py
With Google Artifact Registry, we can use an `RSPImageCollection` to hold all known images, rather than using the more limited `RSPImageTagCollection` because (with Docker) we don't have digests. `RSPImageCollection` therefore needs a `subset` operation to generate the list of prepulled images.
Alias tracking of images was incomplete: it didn't handle the case of multiple aliases pointing to the same image or non-alias tags with the same digest. The flags to `all_images` also hid images based on whether we had ever seen an alias even if that alias wasn't in the same collection, which wasn't desirable. Fix both of those problems by adding more sophisticated alias tracking to `RSPImageCollection`.
Similarly, the code for updating which nodes an image was present on was not sophisticated …
> DM-38466: Move more image operations into RSPImageCollection

- src/jupyterlabcontroller/services/lab.py
- tests/configs/standard/output/lab-objects.json
Inject ACCESS_TOKEN into the environment directly from the secret rather than putting a copy of it into the environment ConfigMap.
> DM-38554: Move ACCESS_TOKEN out of the ConfigMap

- src/jupyterlabcontroller/services/lab.py
- tests/configs/standard/output/lab-objects.json
Now that we always spawn labs by digest, a pull policy of Always isn't doing anything for us other than adding unnecessary polling of the underlying image registry. Switch to IfNotPresent.
> DM-38554: Change lab pull policy to IfNotPresent

- src/jupyterlabcontroller/config.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/storage/k8s.py
- tests/configs/standard/input/config.yaml
- tests/configs/standard/output/lab-objects.json
- tests/settings.py
Rather than listing the pull secret like any other secret and then separating it out if it's named pull-secret, use a separate configuration option specifying the pull secret to copy and explicitly copy it in the lab service independent of creation of other lab secrets.
> DM-38554: Rework how pull secrets are implemented

- src/jupyterlabcontroller/services/lab.py
- tests/configs/standard/output/lab-objects.json
Avoid cryptic abbreviations in environment variables that are exposed to users.
> DM-38554: Rename K8S_NODE_NAME to KUBERNETES_NODE_NAME

- src/jupyterlabcontroller/config.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/storage/k8s.py
- tests/configs/standard/input/config.yaml
- tests/configs/standard/input/test_objects.json
- tests/configs/standard/output/lab-objects.json
To make it easier to transition from the old Nublado, add support for mounting secrets and injecting them as environment variables. Add a test for supplemental secrets in addition to the pull secret.
> DM-38554: Add support for exposing secrets in more ways

- src/jupyterlabcontroller/exceptions.py
- src/jupyterlabcontroller/handlers/form.py
- src/jupyterlabcontroller/handlers/labs.py
- src/jupyterlabcontroller/handlers/user_status.py
- src/jupyterlabcontroller/main.py
- src/jupyterlabcontroller/models/v1/lab.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/services/source/docker.py
- src/jupyterlabcontroller/services/source/gar.py
- src/jupyterlabcontroller/storage/gafaelfawr.py
- tests/handlers/form_test.py
- tests/handlers/labs_test.py
- tests/handlers/user_status_test.py
Previously, the handlers were checking for expected errors and turning them manually into `HTTPException` exceptions. The detail part of those exceptions was generally just a string, rather than the error model the API specification claimed we were using, and each new exception had to be manually caught.
Import an idea from Gafaelfawr where there is a top-level exception class with a global exception handler that understands how to format itself into the error model using class variables that can be set by subclassed exceptions to indicate things like the error code and the HTTP status. Convert all the expected exceptions that should result in normal error codes (not a 500) to be based on that exception class. Annotate the exceptions on the way through with location information about the …
> DM-38554: Use structured exceptions for expected errors

- src/jupyterlabcontroller/models/v1/event.py
- src/jupyterlabcontroller/services/events.py
- src/jupyterlabcontroller/services/lab.py
- tests/configs/standard/output/pod-events.json
- tests/handlers/labs_test.py
My original idea to use separate events for progress and messages to avoid adding another encoding layer turned out to be a poor one. This required worrying about the ordering of messages and more complex logic on both sides, and the httpx-sse library supports decoding a JSON body of a server-sent event. Switch to JSON-encoded messages that include both a message and an optional progress value.
> DM-38554: Switch to JSON events

- src/jupyterlabcontroller/models/domain/usermap.py
- src/jupyterlabcontroller/services/lab.py
- tests/handlers/labs_test.py
- tests/handlers/user_status_test.py
This is a temporary hack so that the pod state is not completely wrong. The status request should check to see if the pod is there rather than just trusting it is based on internal state, but that's not a release blocker and thus a problem for another day.
> DM-38554: Update pod state in user status during spawn

- src/jupyterlabcontroller/services/lab.py
- tests/configs/standard/output/pod-events.json
- tests/handlers/labs_test.py
Sending separate progress events for the creation of every type of object spams the event list and tends to push the interesting events towards or off the bottom of the screen. Since all those events are identical every time, only emit events for creating the namespace and the supporting resources.
Tweak the percentages based on my subjective impression of what steps take the most time, leaving more room for the pod spawning itself. Use 75% as the threshold at which we hand control back to JupyterHub and wait for the lab to start.
Remove the username from every progress message. Since the progress messages are only returned by calling a user-specific endpoint, this seems pointless. Instead, only mention the user in the first and last messages.
> DM-38554: Improvements to lab spawn messages

- src/jupyterlabcontroller/services/lab.py
When reconstructing internal state from Kubernetes after a restart, it's normal to encounter user labs that are not present in the internal state. Log this at info level rather than warning.
> DM-38554: Reduce severity of state recreation log message

- src/jupyterlabcontroller/handlers/form.py
- src/jupyterlabcontroller/handlers/labs.py
- src/jupyterlabcontroller/handlers/user_status.py
Various routes of the lab controller pull information from the X-Auth-Request-User and X-Auth-Request-Token headers, set by Gafaelfawr. By default, FastAPI includes that in the OpenAPI schema, but in this case this is an internal implementation detail of our authentication system and the client should never send these headers. Mark them as not included in the schema.
> DM-38554: Do not include Gafaelfawr headers in schema

- src/jupyterlabcontroller/config.py
- src/jupyterlabcontroller/constants.py
- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/services/prepuller.py
- src/jupyterlabcontroller/storage/k8s.py
- tests/configs/standard/input/metadata/name
- tests/configs/standard/input/metadata/uid
- tests/configs/standard/output/prepull-objects.json
- tests/services/prepuller_test.py
- tests/support/config.py
Use the injected pod metadata for the lab controller to mark the prepull pods as owned by the lab controller. Set block owner deletion to try to force cleanup of the prepull pods before restarting the lab controller, to reduce conflicts after restart.
> DM-38554: Add ownership information to prepull pods

- src/jupyterlabcontroller/models/domain/rspimage.py
- src/jupyterlabcontroller/services/source/gar.py
- src/jupyterlabcontroller/storage/gar.py
- tests/configs/gar-cycle/input/config.yaml
- tests/configs/gar-cycle/input/known-images.json
- tests/configs/gar-cycle/input/nodes.json
- tests/configs/gar-cycle/output/images.json
- tests/configs/gar-cycle/output/menu.json
- tests/services/prepuller_test.py
- tests/support/data.py
Cycle filtering wasn't implemented on RSPImageCollection or plumbed through to the Google Artifact Registry storage layer. Do that, and add a test suite for cycle handling with Google Artifact Registry as well.
This uncovered a few more capitalization problems when an unknown tag with a cycle is later resolved into an alias. Fix those by always title-casing the display name when resolving the alias.
> DM-38554: Fix cycle handling with Google Artifact Registry

- src/jupyterlabcontroller/exceptions.py
- src/jupyterlabcontroller/main.py
Rename the parent exception for errors in the request that should be reported with normal HTTP status codes from ValidationError to ClientRequestError, and update the documentation. ValidationError is too specific and also conflicts with the name of a Pydantic exception.
> DM-38554: Rename ValidationError to ClientRequestError

- src/jupyterlabcontroller/exceptions.py
- src/jupyterlabcontroller/storage/docker.py
- src/jupyterlabcontroller/storage/gafaelfawr.py
Add a class that understands httpx exceptions and derive Gafaelfawr and Docker exceptions from that class. Separate out the Gafaelfawr exception from parsing the result in a separate exception that understands Pydantic errors. These new exception classes support Slack reporting, which is not yet used but will be in an upcoming change.
> DM-38554: Add Slack-reportable structured web exceptions

- src/jupyterlabcontroller/services/lab.py
- tests/configs/standard/output/lab-objects.json
Our init container implementation depended on these variables, even though the main lab no longer does. Set them directly for init containers.
> DM-38554: Set EXTERNAL_{UID,GID} for init containers

- src/jupyterlabcontroller/handlers/labs.py
- src/jupyterlabcontroller/handlers/user_status.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/storage/docker.py
- src/jupyterlabcontroller/storage/gafaelfawr.py
- src/jupyterlabcontroller/storage/gar.py
- src/jupyterlabcontroller/storage/k8s.py
Bind the structlog logger with additional information where available, primarily the username and the name and namespace of Kubernetes objects. Use that rather than interpolating that data into the logger message so that it can be used in queries in log systems such as Google Log Explorer.
Add debug logging for the storage layer, since that seems likely to be useful in the future.
> DM-38554: Improved structured logging

- src/jupyterlabcontroller/main.py
The URL for the OpenAPI documentation incorrectly had an extra leading slash. Remove the extraneous slash.
> DM-38795: Fix API documentation

- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/storage/k8s.py
Rather than maintaining a global K8sStorageClient, just keep a global kubernetes_asyncio client (to maintain the connection pool) and create new K8sStorageClient objects with each request. This will improve the logging by attaching the per-request logger to the K8sStorageClient when spawning labs, so those log messages will get more context.
> DM-38795: Construct a new K8sStorageClient for each request

- src/jupyterlabcontroller/config.py
- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/models/domain/kubernetes.py
- src/jupyterlabcontroller/models/k8s.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/services/prepuller.py
- src/jupyterlabcontroller/services/state.py
- src/jupyterlabcontroller/storage/k8s.py
- tests/handlers/labs_test.py
- tests/services/prepuller_test.py
Merge the method to wait for a pod to start with the method that monitors events for that pod and eliminate the extra background task for event injection. Use that same method for the prepuller.
Add a new configurable spawn timeout instead of hard-coding it, and pass that timeout into the Kubernetes watch, using a shorter watch for the network connection timeout.
This removes the suppression of duplicate messages, since it's a bit more awkward to do in this format. We can add it back in, but I wanted to try running this version first and see to what degree duplicate messages are an issue.
> DM-38795: Merge waiting for pod with event monitoring

- src/jupyterlabcontroller/handlers/labs.py
- src/jupyterlabcontroller/models/domain/lab.py
- src/jupyterlabcontroller/models/v1/event.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/services/state.py
Use the same division of labor between LabManager and LabStateManager as for lab creation, which lets us eliminate more public APIs from LabStateManager for the individual events involved in deletion. As with lab spawning, LabStateManager now handles the exceptions, although lab deletion is done in the foreground since JupyterHub does it in the foreground anyway and therefore no purpose is served by adding background deletion.
> DM-38795: Redo how labs are deleted

- src/jupyterlabcontroller/services/state.py
- src/jupyterlabcontroller/storage/k8s.py
- tests/handlers/labs_test.py
- tests/handlers/user_status_test.py
When polled by JupyterHub, return the actual state of the lab rather than trusting that in-memory data is correct. This supplements the background reconciliation job. Unlike a reconciliation, this doesn't fix data, just moves things into a failed state if the pod should be running and isn't.
> DM-38795: Get the actual state of the lab from Kubernetes

- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/services/state.py
- tests/configs/standard/output/pod-events.json
- tests/handlers/labs_test.py
If the user already has a lab but that lab is in a failed state, allow them to spawn again and delete the existing lab before creating a new one.
> DM-38795: Delete lab on spawn if in failed state

- docs/_rst_epilog.rst
- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/models/v1/lab.py
- src/jupyterlabcontroller/services/builder.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/services/size.py
- src/jupyterlabcontroller/services/state.py
- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/util.py
- tests/configs/standard/output/lab-objects.json
- tests/services/state_test.py
When the lab controller was restarted, its internal data structures were only partly refreshed from the running labs in Kubernetes. A lot of data was missing or incorrect, such as all of the environment variables. This ran afoul of the new validator to ensure that JUPYTERHUB_SERVICE_PREFIX is set.
Fully restore internal state by also reading the ConfigMap and ResourceQuota objects, and add the data that isn't otherwise easily discernable from lab resources (full name and group name information, which only otherwise exist in the templated NSS files) to annotations on the pod.
This introduces a new LabBuilder object, which eventually will hold all the code to construct Kubernetes objects for a user's lab environment (moved from LabManager, which will then only be about managing lab …
> DM-38795: Fix lab state reconciliation

- src/jupyterlabcontroller/services/prepuller.py
- src/jupyterlabcontroller/storage/k8s.py
- tests/configs/standard/output/prepull-conflict-objects.json
- tests/services/prepuller_test.py
When creating a prepuller pod, if a pod already exists with the same name, remove it first. We may sometimes strand prepuller pods when the lab controller is killed while prepulling (assuming Kubernetes doesn't remove the pods due to their ownership metadata), and it's always safe to recreate those pods.
Also remove prepuller pods in any terminal state, not just success, to reduce the chances we leave stranded pods behind.
> DM-38795: Handle conflicts on names of prepuller pods

- requirements/main.in
- requirements/main.txt
The changes for better mocks have been merged, so switch to the main branch of Safir until the new release is out.
> DM-38795: Switch to main branch of Safir

- src/jupyterlabcontroller/exceptions.py
- src/jupyterlabcontroller/services/state.py
- src/jupyterlabcontroller/storage/k8s.py
- tests/services/state_test.py
Use TimeoutError for all timeouts instead of our own separate exception. Add timeout handling to lab spawning and deletion, and test that timeout handling works properly.
> DM-38795: Handle timeouts consistently

- src/jupyterlabcontroller/services/prepuller.py
- src/jupyterlabcontroller/services/state.py
- src/jupyterlabcontroller/storage/k8s.py
- tests/handlers/labs_test.py
- tests/services/prepuller_test.py
- tests/services/state_test.py
Unfortunately, Kubernetes doesn't create an event when a pod changes phase to running, so the approach of only watching Kubernetes namespace events and checking the pod phase when an event is received doesn't work. This required going back to watching the pod phase and the namespace events in separate tasks. The task management of the event watch task is now done by the pod watch task instead of by `LabManager`.
> DM-38795: Use a pod watch to wait for pods to start

- src/jupyterlabcontroller/services/lab.py
- tests/configs/standard/output/lab-objects.json
lsst.rsp already looks for the environment variable K8S_NODE_NAME, so while we want to avoid confusing abbreviations, we need to set both that and KUBERNETES_NODE_NAME for now until lsst.rsp has been updated and rolled out in a new weekly and recommended.
> DM-38425: Set K8S_NODE_NAME for now

- src/jupyterlabcontroller/assets/form_template.txt
- tests/configs/standard/output/lab_form.txt
In order to move the selection to the dropdown when an image was selected from the dropdown, we were using the onclick attribute of the <select> element. This appears to not work correctly with Safari. Change it to onchange, which hopefully will.
See https://stackoverflow.com/questions/1769374/
> DM-39249: Fix JavaScript for selecting images from dropdown

- src/jupyterlabcontroller/config.py
- src/jupyterlabcontroller/services/builder.py
- tests/configs/standard/input/config.yaml
- tests/configs/standard/output/lab-objects.json
USDF dev mounts a volume in one place and a subpath of the same volume in a different place. Add support for specifying a subPath in the volume list.
This is not entirely correct since we still generate two PVCs for the same storage, which I think will work at the USDF because everything is ReadWriteMany, but which would fail with ReadWriteOnce. However, the more correct solution requires a more intrusive configuration change to support mounting the same volume in multiple places, which I'm deferring for later work.
> DM-39232: Add support for subPath in volume mounts

- requirements/main.in
- requirements/main.txt
- src/jupyterlabcontroller/main.py
sse-starlette initializes itself on first use with a process-global lock that's bound to the current event loop, which caused tests to fail when each test was run under a separate event loop. Clean up this lock on server shutdown to avoid this problem.
> DM-39249: Work around a per-event-loop lock in sse-starlette

- src/jupyterlabcontroller/models/v1/lab.py
- src/jupyterlabcontroller/services/lab.py
- tests/configs/standard/input/test_objects.json
- tests/handlers/labs_test.py
- tests/handlers/user_status_test.py
Gafaelfawr allows the user to be a member of a group with no GID, but this should be ignored for Nublado controller purposes since we can't do anything useful with such groups. Filter them out when constructing the lab and when constructing the user metadata portion of the lab status.
Take advantage of the opportunity to refactor the method that generates the NSS ConfigMap.
> DM-39400: Handle groups without GIDs

- src/jupyterlabcontroller/services/lab.py
- tests/configs/standard/output/lab-objects.json
- tests/handlers/working_dir_test.py
- tests/services/homedir_test.py
At USDF, despite our homedir_schema setting, we're creating /home/<username>
I believe this fixes the issue, although I'm not going to merge until I've done some testing at USDF-dev.
The cause appears to be 1) not setting run_as_user in the pod spec, so despite the fact that you end up as the right user with the right groups, it starts with enough privilege to create the directory), which 2) is set as working_dir in the pod spec.
So I've corrected these two things.
In an idea world we would have a test for the pod spec being correct when a non-default homedir_schema is in effect, but we didn't make it easy to unit test pod spec creation, which (necessarily) relies on resolved RSPImages, and therefore needs a bunch of new helper methods defined, or an end-to-end handler test (which might …
> tickets/DM-40183: fix incorrect homedir creation at USDF

- Makefile
Add a help target to the Makefile summarizing the available targets. Make that target the default. Use the new tox syntax for the run target.
> DM-40638: Update Makefile targets

- .github/workflows/dependencies.yaml
- .github/workflows/periodic-ci.yaml
Add a periodic GitHub Action workflow to check whether updating dependencies would cause tests to fail. Add a periodic GitHub Action workflow to update pre-commit dependencies automatically.
> DM-40638: Add dependency GitHub Actions

- src/jupyterlabcontroller/models/domain/kubernetes.py
- src/jupyterlabcontroller/services/fileserver.py
- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/storage/kubernetes/watcher.py
Add a generic Kubernetes watcher class with proper typing for the objects that it returns, built on the assumption that the Kubernetes library will properly decode Kubernetes objects in the watch events. For now, use it only to watch for pod status; the other uses of watches in the Kubernetes storage layer will be replaced in upcoming changes.
After some experimentation, this uses a different approach than the callback approach currently used in the storage layer for watches. Instead, the watch exposes an async interator with structured events with appropriate typing, allowing any analysis to be done in the body of the async for loop.
> DM-40691: Add a new generic Kubernetes object watcher

- docs/_rst_epilog.rst
- src/jupyterlabcontroller/constants.py
- src/jupyterlabcontroller/models/domain/kubernetes.py
- src/jupyterlabcontroller/services/fileserver.py
- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/storage/kubernetes/creator.py
- src/jupyterlabcontroller/storage/kubernetes/deleter.py
Add a couple of classes that provide generic Kubernetes storage access, one to types where we only do create and read and another for types where we also do list and delete. Support deleting the old resource on conflicts for the latter type. Instantiate classes for ConfigMap and Service management from those generic classes and use them in the Kubernetes storage layer.
> DM-40691: Add new generic Kubernetes storage layer

- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/storage/kubernetes/creator.py
Use the generic storage layer to provide storage for Secret, NetworkPolicy, PersistentVolumeClaim, and ResourceQuota objects.
> DM-40691: Use generic Kubernetes storage for more kinds

- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/storage/kubernetes/namespace.py
- tests/handlers/labs_test.py
Replace the direct calls to the Kubernetes namespace API with a new NamespaceStorage class in the new style. This class is entirely separate from those based on KubernetesObjectDeleter even though there is some duplication of code, since the namespace API is fundamentally different (only a name, no namespace).
Preserve the more complex timeout handling for namespace deletion since it is most likely to have timeout issues. This may be worth implementing for all deleter objects, but that's a problem for a future day.
> DM-40691: Add a new-style NamespaceStorage class

- src/jupyterlabcontroller/models/domain/kubernetes.py
- src/jupyterlabcontroller/services/fileserver.py
- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/storage/kubernetes/deleter.py
- src/jupyterlabcontroller/storage/kubernetes/ingress.py
- tests/configs/fileserver/input/config.yaml
- tests/fileserver/handlers/timeout_test.py
- tests/fileserver/handlers/wait_for_ingress.py
Replace the Kubernetes job manipulation classes with a JobStorage class that inherits from KubernetesObjectDeleter. Add propagation_policy support to the standard delete method to support its usage with jobs.
Replace the Kubernetes ingress calls with a new-style IngressStorage class. This inherits the standard functionality from the generic KubernetesObjectDeleter class, but adds a method to check whether an ingress has an IP address assigned and a method to wait for an ingress to appear and get an IP address.
This uncovered a bug that meant that the code waiting for the ingress and job to be deleted was doing nothing due to a missing f in an f-string. Fixing that in turn required some changes to the test suite, since it was often not deleting the ingress until after the controller was …
> DM-40691: Add new JobStorage and IngressStorage classes

- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/models/domain/kubernetes.py
- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/storage/kubernetes/deleter.py
- src/jupyterlabcontroller/storage/kubernetes/pod.py
- src/jupyterlabcontroller/storage/kubernetes/watcher.py
- tests/fileserver/handlers/object_cleanup_on_exit_test.py
Add a new PodStorage class based on KubernetesObjectDeleter. Move a generic function for waiting for pod phases to it, and call that function instead of doing the watch directly in K8sStorageClient. Move the async iterator for pod events into that class as well, and change it to use the new KubernetesWatcher class.
Pods had several features that other types didn't need, so add them to the generic layer: proper timeout tracking on watches in case the server times us out before our timeout was reached, grace period on object deletion, and listing with a label selector.
Use a custom logger for watches from the new storage layer so that any log messages produced by the watch will include the object name and namespace when appropriate. Also fix the KubernetesWatcher object to not destructively …
> DM-40691: Add a new pod storage layer

- src/jupyterlabcontroller/models/domain/kubernetes.py
- src/jupyterlabcontroller/services/state.py
- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/storage/kubernetes/pod.py
- tests/fileserver/handlers/object_cleanup_on_exit_test.py
- tests/handlers/labs_test.py
- tests/handlers/user_status_test.py
- tests/services/prepuller_test.py
- tests/services/state_test.py
This is the only type of pod that we could be talking about, so the new name is not ambiguous, and we use this in various places where saving some characters means nicer formatting.
> DM-40691: Rename KubernetesPodPhase to PodPhase

- docs/_rst_epilog.rst
- src/jupyterlabcontroller/constants.py
- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/services/builder.py
- src/jupyterlabcontroller/services/prepuller.py
- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/storage/metadata.py
- tests/configs/gar/input/metadata/name
- tests/configs/gar/input/metadata/namespace
- tests/configs/gar/input/metadata/uid
- tests/configs/standard/input/metadata/namespace
- tests/configs/standard/output/prepull-conflict-objects.json
- tests/configs/standard/output/prepull-objects.json
- tests/services/prepuller_test.py
Model the new separation between builder objects, services, and the Kubernetes storage layer with the prepuller, which is the simplest. Add a new PrepullerBuilder that constructs the pod that the prepuller uses, and have it use that and the PodStorage storage layer directly, so it no longer needs K8sStorageClient.
Introduce a new MetadataStorage layer, which is resposible for getting metadata about the running pod from the Kubernetes downward API, and use it for namespace and object reference information for the prepuller pods.
Stop using the namespace prefix for labs as the namespace for prepuller pods and always use the namespace from the downward API. Make the downward API information mandatory; there's really no reason not to have it.
Stop adding Argo CD annotations to the prepuller …
> DM-40813: Refactor prepuller storage layer

- src/jupyterlabcontroller/constants.py
- src/jupyterlabcontroller/storage/k8s.py
Pull the default Argo CD annotations for lab and file server objects out of the storage layer and into a constant.
> DM-40813: Move Argo CD annotations into a constant

- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/services/image.py
- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/storage/kubernetes/node.py
Continuing the disassembly of K8sStorageClient into smaller classes, move get_image_data to get image information from that class into a new NodeStorage class, which is now the only Kubernetes storage required by the ImageService.
> DM-40813: Move node storage into its own class

- src/jupyterlabcontroller/dependencies/context.py
- tests/conftest.py
- tests/fileserver/conftest.py
- tests/handlers/extra_annotations_test.py
- tests/handlers/labs_test.py
- tests/handlers/volume_cases_test.py
- tests/services/prepuller_test.py
- tests/support/config.py
If a test version of the controller is running and a test case calls configure, automatically reset the process context to use the new configuration.
> DM-40813: Automatically reconfigure running test apps

- src/jupyterlabcontroller/config.py
- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/models/domain/fileserver.py
- src/jupyterlabcontroller/models/domain/lab.py
- src/jupyterlabcontroller/models/domain/volumes.py
- src/jupyterlabcontroller/services/builder/fileserver.py
- src/jupyterlabcontroller/services/builder/lab.py
- src/jupyterlabcontroller/services/builder/volumes.py
- src/jupyterlabcontroller/services/fileserver.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/storage/k8s.py
- src/jupyterlabcontroller/storage/kubernetes/fileserver.py
- src/jupyterlabcontroller/storage/kubernetes/lab.py
- src/jupyterlabcontroller/storage/kubernetes/pod.py
- src/jupyterlabcontroller/storage/kubernetes/watcher.py
- tests/configs/fileserver/input/config.yaml
- tests/fileserver/handlers/object_cleanup_on_exit_test.py
- tests/services/state_test.py
Follow the new builder pattern for fileserver object creation and move the Kubernetes object construction into FileserverBuilder. Move construction of Kubernetes classes for volumes and volume mounts into another small class that can be used by both the LabBuilder and the FileserverBuilder. Move most of the storage layer for the fileserver into a new storage class.
The storage object migration is not yet complete because of state management and the calls to reconstruct state from Kubernetes objects. That redesign will be handled in a subsequent redesign of the separation between the manager and state classes to prepare for Redis separation, after which the old Kubernetes storage layer can be retired completely.
This surfaced a problem with the new watcher class. It was rounding down …
> DM-40813: Move fileserver object creation into a builder

- src/jupyterlabcontroller/exceptions.py
Switch the argument order to take name first followed by namespace. This is less intuitive but every Kubernetes API uses this ordering, so trying to use a more "natural" order just creates bugs.
> DM-41051: Fix arguments to MissingSecretError

- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/services/lab.py
- tests/configs/extra-annotations/input/metadata
- tests/configs/volume-cases/input/metadata
- tests/conftest.py
- tests/handlers/labs_test.py
- tests/services/state_test.py
When creating the lab secret, the lab service was still using the namespace prefix for user namespaces as a namespace from which to read secrets, instead of using the namespace of the controller itself. Convert the lab manager to the new MetadataStorage layer so that it is consistent with the rest of the controller, and fix the test suite accordingly.
> DM-41051: Use controller namespace as secret source

- src/jupyterlabcontroller/exceptions.py
- src/jupyterlabcontroller/main.py
- src/jupyterlabcontroller/services/fileserver.py
To make testing easier and allow enabling of the fileserver after the FastAPI application has been started, unconditionally register the fileserver routes but raise exceptions in the fileserver state manager if it's not enabled. Change DisabledError to NotConfiguredError to match the exception for the same purpose in Gafaelfawr and configure it to translate into 404 errors for users.
> DM-41051: Redo how disabled fileserver is handled

- src/jupyterlabcontroller/models/domain/gafaelfawr.py
- tests/conftest.py
- tests/fileserver/handlers/fileserver_test.py
- tests/fileserver/handlers/object_cleanup_on_exit_test.py
- tests/fileserver/handlers/timeout_test.py
- tests/fileserver/handlers/wait_for_ingress.py
- tests/handlers/extra_annotations_test.py
- tests/handlers/form_test.py
- tests/handlers/labs_test.py
- tests/handlers/user_status_test.py
- tests/handlers/volume_cases_test.py
- tests/services/state_test.py
- tests/support/gafaelfawr.py
Take advantage of the new `GafaelfawrUser` model to return a single object instead of separate token and user fixtures, and add a method to it to turn a user back into the headers that would be sent by Gafaelfawr as a convenience for tests. Use that everywhere instead of constructing the headers manually except in places where the manual construction adds more test surface.
> DM-41051: Streamline test user handling

- src/jupyterlabcontroller/config.py
- src/jupyterlabcontroller/services/builder/lab.py
- tests/data/homedir-schema/input/config.yaml
- tests/data/homedir-schema/output/passwd
- tests/handlers/labs_test.py
Allow the prefix for home directories (normally /home) and the suffix (normally empty, but allowing the home directory for labs to be a subdirectory of the user's normal home directory) to be configured.
I picked this approach over adding template support because I don't like having to document a template language in user documentation and try to explain what variables are available and how to write a template. In this case, I think the three options are reasonably easy to understand and avoid the need for a full-blown templating mini-language.
> DM-41051: Add support for homedir prefix and suffix

- src/jupyterlabcontroller/exceptions.py
- src/jupyterlabcontroller/main.py
Safir now provides ClientRequestError (and its handler) and SlackWebException, with some improvements. Use those exceptions from Safir rather than defining our own.
> DM-41350: Use Safir ClientRequestError and SlackWebException

- src/jupyterlabcontroller/models/v1/lab.py
- src/jupyterlabcontroller/services/lab.py
- tests/handlers/labs_test.py
- tests/services/lab_test.py
Rather than rolling terminated pods into the error status, track them separately, still allowing them to be automatically deleted when a new spawn is requested. Add some more logging on spawn conflicts to aid in debugging.
This does not yet clean up terminated pods, just enables proper state tracking for them so that they can be cleaned up in a subsequent change.
> DM-41350: Properly track terminated pods

- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/models/v1/lab.py
- src/jupyterlabcontroller/services/lab.py
- tests/handlers/labs_test.py
- tests/handlers/user_status_test.py
- tests/services/lab_test.py
When we encounter a lab in a terminated state during background reconciliation (labs that were OOMKilled, idle-culled, etc.), delete the lab. Do this carefully to avoid conflicts with a user operation that might race with us, since it should get precedence. Similarly clean up labs that are in a failed state.
Convert a pod status of Failed to a lab status of terminated, not failed. Use failed to indicate missing Kubernetes resources or similar errors, and terminated to mean that the pod has stopped for whatever reason.
> DM-41350: Delete not-running labs during reconciliation

- src/jupyterlabcontroller/dependencies/context.py
- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/handlers/fileserver.py
- src/jupyterlabcontroller/services/fileserver.py
Lift checks for whether the file server is enabled into the ProcessContext and RequestContext and remove the checks in front of all of the public methods of FileserverManager. Rename FileserverStateManager to FileserverManager to parallel LabManager.
> DM-41188: Move file server enabled checks

- src/jupyterlabcontroller/constants.py
- src/jupyterlabcontroller/factory.py
- src/jupyterlabcontroller/models/domain/kubernetes.py
- src/jupyterlabcontroller/services/builder/fileserver.py
- src/jupyterlabcontroller/services/fileserver.py
- src/jupyterlabcontroller/services/lab.py
- src/jupyterlabcontroller/storage/kubernetes/fileserver.py
- src/jupyterlabcontroller/storage/kubernetes/pod.py
Use the same pattern as the new state management in LabManager: a dictionary of state objects per user, where the user is never removed once we've seen them. In this case, the state object only needs to hold a lock, not a full-blown manager class.
Rather than spawning a separate background task (and Kubernetes watch) for every running file server, use a single background task that watches for all pod changes in the namespace. Use that to catch pod phase changes. Add a background reconcile task to look for any other problems (such as Kubernetes object deletion) and clean up after those.
Add Slack reporting of errors in file server operations.
> DM-41188: Rework state management for file servers

- .pre-commit-config.yaml
- pyproject.toml
Ruff can now also do formatting, so use it and reduce the number of linter programs we use. Disable the Ruff warnings that the Ruff documentation says should be disabled when using ruff format.
We unfortunately still have to use black via blacken-docs for formatting examples in documentation. A native Ruff replacement is still some time off.
> DM-41595: Use ruff format instead of black

- controller/src/controller/exceptions.py
- controller/src/controller/services/lab.py
- controller/src/controller/storage/kubernetes/watcher.py
We saw one production exception indicating the Kubernetes API returned a 410 error on an event watch during lab startup, even though no resourceVersion was specified. Various things on-line indicate that this is known and expected for long-lasting watches, although this particular watch shouldn't have lasted long enough to trigger it.
Nonetheless, the correct behavior appears to be to retry all 410 errors even if no resourceVersion was set. Do that, but add a one second delay so that we don't spam the Kubernetes API with requests if all requests are returning 410.
Improve exception reporting when a namespace and object type are set but no object name, which is common with watches.
The pod event watch is purely informational, but we were aborting the spawn if the event watch died with an …
> DM-41613: Harden lab spawning against event watch errors

- controller/src/controller/services/lab.py
- controller/src/controller/storage/kubernetes/custom.py
- controller/src/controller/storage/kubernetes/deleter.py
- controller/src/controller/storage/kubernetes/fileserver.py
- controller/src/controller/storage/kubernetes/lab.py
- controller/src/controller/storage/kubernetes/namespace.py
- controller/src/controller/storage/kubernetes/pod.py
- controller/src/controller/storage/kubernetes/watcher.py
Force all Kubernetes watches to have timeouts or explicitly set timeout to None, and ensure the latter is only done for the background task waiting for file server pods to complete. Everythig else now has a timeout, although often this is KUBERNETES_DELETE_TIMEOUT for deletions and replacements.
Add explicit asyncio.timeout calls around watches rather than relying on the timeout handling of the underlying Kubernetes library, since it seems a little underdocumented. Make timeout arguments to more lower-level storage functions mandatory.
Add a timeout around the watch for pod events during spawn.
> DM-41622: Add more timeouts on Kubernetes operations

- controller/src/controller/factory.py
Use match rather than if statements testing isinstance when constructing the image source for the prepuller in the controller ProcessContext.
> DM-41630: Use match when constructing prepuller source

- controller/src/controller/dependencies/config.py
- controller/src/controller/handlers/fileserver.py
- controller/src/controller/handlers/index.py
- controller/src/controller/main.py
- controller/tests/support/config.py
Rename configuration_dependency to config_dependency to parallel other packages and to match the name of the implementation class.
> DM-41630: Rename configuration_dependency

- controller/src/controller/factory.py
This method is no longer used anywhere.
> DM-41630: Remove Factory create_slack_client method

- controller/src/controller/config.py
Expand the description of the configuration option that determines whether the file server is enabled.
> DM-41630: Improve description of fileserver.enabled config

- controller/src/controller/factory.py
- controller/src/controller/services/builder/fileserver.py
Rename instance_url to base_url to match the name of the configuration option and stay more consistent with the rest of the source.
> DM-41630: Rename instance_url in FileserverBuilder

- controller/src/controller/models/v1/lab.py
In the API documentation for lab creation, document that reset_env also moves aside the .conda directory.
> DM-41630: Add .conda to documentation of reset_env

- controller/src/controller/factory.py
- controller/src/controller/services/builder/lab.py
- controller/src/controller/services/fileserver.py
- controller/src/controller/services/lab.py
Always use base_url, not instance_url, for that configuration setting. Remove it from FileserverManager, which no longer needs it.
> DM-41630: Standardize base_url handling in controller

- controller/src/controller/templates/spawner.html.jinja
- controller/tests/data/standard/output/lab-form.html
Be more careful about whitespace management in the spawner form and put selections on single lines to make the output a bit more readable by humans and with fewer stray stranded angle brackets.
> DM-41630: Clean up formatting of spawner form

- controller/src/controller/config.py
- controller/src/controller/models/v1/prepuller_config.py
- controller/tests/data/standard/input/config.yaml
Configure all of the controller configuration models to disallow unknown fields. Now that Pydantic v2 supports the equivalent of CamelCaseModel except for changing the model_dump defaults, switch to using Pydantic v2 native functions instead of Safir.
> DM-41630: Disallow unknown controller config options

- controller/src/controller/config.py
- controller/src/controller/constants.py
- controller/src/controller/factory.py
- controller/src/controller/models/v1/prepuller_config.py
- controller/tests/conftest.py
- controller/tests/storage/docker_test.py
- controller/tests/support/config.py
The path to a Docker credentials file was configured at the top level of the Nublado controller configuration, but this file is only used if the prepuller is configured with a Docker image source. Move this setting into the Docker image source model, but mark it as not exported since we don't want to return this field when queried for prepuller status via the API.
> DM-41630: Move Docker credentials configuration

- controller/src/controller/config.py
- controller/src/controller/handlers/fileserver.py
- controller/src/controller/services/builder/fileserver.py
- controller/src/controller/templates/fileserver.html.jinja
- controller/tests/data/fileserver/output/fileserver.html
The file server was always appending /files to path_prefix, which somewhat defeats the point of having a path prefix. Move /files to be the default value of path_prefix and stop appending /files.
Fix the creation of the per-user file server ingress to correctly honor path_prefix.
> DM-41630: Fix file server path_prefix

- controller/src/controller/services/builder/prepuller.py
- controller/tests/data/standard/output/prepull-conflict-objects.json
- controller/tests/data/standard/output/prepull-objects.json
Rather than sleeping five seconds after starting a prepuller container, allow it to exit immediately so that prepullers can complete somewhat faster.
> DM-41630: Remove unnecessary delay in prepuller pods

- controller/src/controller/config.py
- controller/tests/data/cycle/input/config.yaml
- controller/tests/data/extra-annotations/input/config.yaml
- controller/tests/data/fileserver/input/config.yaml
- controller/tests/data/gar-cycle/input/config.yaml
- controller/tests/data/gar/input/config.yaml
- controller/tests/data/homedir-schema/input/config.yaml
- controller/tests/data/standard/input/config.yaml
Rather than using a complicated default of an environment variable we don't use and the namespace in which the controller is running, require the namespace prefix be explicitly configured. Explicit configuration is often better than obscure defaults.
> DM-41630: Require setting the namespace prefix for labs

- controller/src/controller/exceptions.py
- controller/src/controller/services/lab.py
- controller/tests/handlers/labs_test.py
The model checking ensured that the requested lab size was a valid member of the enum, but not that it was one of the configured sizes. This could have resulted in a run-time KeyError if the user sent an invalid size. Catch this error explicitly and return a 422 error instead.
> DM-41630: Diagnose invalid lab size on creation

- controller/src/controller/models/domain/image.py
- controller/src/controller/services/image.py
- controller/src/controller/services/source/base.py
- controller/src/controller/services/source/docker.py
- controller/src/controller/services/source/gar.py
There is no longer a separate FormService, so putting the models returned by the image service in controller.models.domain.form felt weird. Rename that module to controller.models.domain.image since it is used by the image service.
> DM-41630: Move domain images for spawner form construction

- controller/src/controller/config.py
- controller/src/controller/services/builder/lab.py
- controller/tests/data/extra-annotations/input/config.yaml
- controller/tests/data/homedir-schema/input/config.yaml
- controller/tests/data/standard/input/config.yaml
Combining NSS base configuration (/etc/passwd and /etc/group) with simple files using an oddly-named modify boolean was confusing and required unnecessary config structure. Move the base /etc/passwd and /etc/group files into their own nss key and turn files into simple key/value pairs of file paths to file contents.
Diagnose attempts to define /etc/passwd and /etc/group via files and reject them when validating the configuration.
Create simple defaults for /etc/passwd and /etc/group containing only the root account, mostly to simplify test setup.
> DM-41630: Separate NSS configuration from simple files

- controller/src/controller/config.py
- controller/src/controller/models/v1/lab.py
- controller/src/controller/units.py
- controller/tests/models/v1/lab_test.py
- controller/tests/units_test.py
The resource constraints on the file server reused the existing ResourceQuantity model, which meant that memory limits and requests had to be specified in bytes. Lift the bitmath utility function into a new module for unit conversions and use it for both lab sizes and for validation of ResourceQuantity, allowing use of SI and NIST suffixes.
Switch to using bitmath's parse_string_unsafe, which handles the lack of a B suffix, supports K instead of k, and otherwise more closely matches the resource language used by Kubernetes.
> DM-41630: Allow use of SI units for file server resources

- controller/src/controller/handlers/files.py
- controller/src/controller/handlers/fileserver.py
- controller/src/controller/main.py
- controller/tests/handlers/files_test.py
Separate the route for the user /files handler into a separate module so that we aren't juggling two routers in the same handler module. Move the long comment explaining how this handler works into the module documentation.
> DM-41630: Reorganize file server routes

- controller/src/controller/exceptions.py
- controller/src/controller/handlers/form.py
- controller/src/controller/handlers/labs.py
- controller/src/controller/models/domain/gafaelfawr.py
- controller/src/controller/services/lab.py
- controller/tests/data/standard/input/config.yaml
- controller/tests/data/standard/output/lab-form.html
- controller/tests/handlers/form_test.py
- controller/tests/handlers/labs_test.py
Do not display lab sizes that are larger than the user's quota in the spawner menu, and reject attempts to create labs larger than the user's quota in the LabManager.
> DM-41630: Filter available labs by the user's quota

- controller/src/controller/config.py
- controller/src/controller/constants.py
- pyproject.toml
/tmp for lab pods is (currently) always an emptyDir ephemeral storage file system. Ensure that no one mounts a file or volume over top of it. Also prevent mounting volumes on /etc/passwd and /etc/group, not that this is likely.
> DM-41630: Prevent mounting over /tmp

- controller/src/controller/config.py
- controller/src/controller/constants.py
Diagnose attempts to set reserved environment variables to static values in the Nublado controller configuration. Reserve all variables starting with JUPYTERHUB_ for the JupyterHub to lab interface.
> DM-41630: Reject setting reserved env variables

- controller/src/controller/exceptions.py
- controller/src/controller/services/lab.py
There was a race condition between the background task to reap completed lab operations and lab deletions. Deletions are started and then immediately waited for, which means they could be collected by the handler between the point the background task sees they are done and the point where it tries to reap them. It should be safe to ignore this race in the background reaper task, since it's only point is to reap tasks that no one else has waited for, so give that exception a custom class and suppress it.
> DM-41630: Handle race condition reaping lab deletions

- controller/src/controller/storage/kubernetes/custom.py
- controller/src/controller/storage/kubernetes/deleter.py
- controller/src/controller/storage/kubernetes/fileserver.py
Restore the propagation policy on file server job deletes that was lost during a refactoring, and add a propagation policy to deleting the GafaelfawrIngress as well in the hope that this will force faster deletion of the derived Ingress.
> DM-41630: Add propagation policy to file server deletes

- controller/src/controller/constants.py
- controller/src/controller/storage/kubernetes/creator.py
- controller/src/controller/storage/kubernetes/custom.py
- controller/src/controller/storage/kubernetes/deleter.py
- controller/src/controller/storage/kubernetes/namespace.py
- controller/src/controller/storage/kubernetes/node.py
The default request timeout in kubernetes_asyncio if none is given is five minutes, which is rather long. We were already setting request timeouts for any watches. Set a shorter request timeout of one minute for other operations so that we don't wait too long if the Kubernetes control plane is not responding.
This timeout is currently hard-coded, but this change makes it possible to make it configurable in the future.
> DM-41630: Add request timeouts to all Kubernetes calls

- .github/workflows/ci.yaml
- controller/requirements/dev.in
- controller/requirements/dev.txt
- docs/dev/development.rst
- noxfile.py
Since the controller and hub use separate frozen dependencies, they should use entirely separate testing sessions for both mypy and pytest. Separate JupyterHub plugin type checking into typing-hub, and clean up the dependency installation.
Remove mypy and pre-commit from dev dependencies for the controller since they aren't used in controller tests. Their installation is properly handled by nox.
Improve the logic for deciding which tests to run when pytest is given arguments, although this is now mostly useful for the test-hub session.
> DM-41630: Further separate controller and hub testing

- .github/workflows/ci.yaml
- Dockerfile.controller
- Dockerfile.hub
- controller/scripts/start.sh
Fix various Docker build issues with the new vertical monorepo setup:
- Fix the start command for the Nublado controller to use the correct Python module name
- Use the correct Dockerfile when building the JupyterHub image
- Install the correct controller package and not some random package named controller from PyPI
- Do not install dependencies for JupyterHub modules, since for some reason that downgrades JupyterHub
> DM-41630: Fix Nublado Docker image build issues

- controller/src/controller/config.py
- controller/src/controller/handlers/form.py
- controller/src/controller/services/builder/lab.py
- controller/src/controller/services/lab.py
- controller/src/controller/templates/spawner.html.jinja
- controller/tests/data/cycle/input/config.yaml
- controller/tests/data/extra-annotations/input/config.yaml
- controller/tests/data/fileserver/input/config.yaml
- controller/tests/data/gar-cycle/input/config.yaml
- controller/tests/data/gar/input/config.yaml
- controller/tests/data/homedir-schema/input/config.yaml
- controller/tests/data/standard/input/config.yaml
- controller/tests/handlers/labs_test.py
- controller/tests/handlers/user_status_test.py
- controller/tests/services/lab_test.py
Either Argo CD or Helm sorts the keys of a dict in a chart configuration before applying the chart, so using a dict for lab sizes does not preserve order. Change it to a list and add a helper function to retrieve the definition for a specific size.
> DM-41630: Use a list for lab sizes instead of a dict

- noxfile.py
When refactoring the test support to further separate JupyterHub from the Nublado controller, the support for running specific tests was accidentally removed. Re-add that.
> DM-41708: Fix nox -s test with specific files

- noxfile.py
When building the lint nox session, upgrade pre-commit instead of just installing it.
> DM-41708: Upgrade pre-commit in lint nox session

- controller/src/controller/handlers/files.py
- controller/src/controller/services/builder/fileserver.py
- controller/src/controller/services/fileserver.py
The file server was taking a UserInfo parameter, but we were actually passing in a GafaelfawrUser model. This happened to work because the fields had the same name, but it was incorrect. Switch all of the types to GafaelfawrUserInfo instead.
> DM-41708: Use GafaelfawrUserInfo for file server creation

- controller/src/controller/services/builder/fileserver.py
Use the GafaelfawrUserInfo property to generate supplemental groups, which excludes groups without a GID.
> DM-41708: Fix supplemental groups for the file server

- controller/src/controller/config.py
- controller/src/controller/constants.py
- controller/src/controller/factory.py
- controller/src/controller/models/domain/fileserver.py
- controller/src/controller/models/domain/kubernetes.py
- controller/src/controller/services/builder/fileserver.py
- controller/src/controller/services/builder/lab.py
- controller/src/controller/services/builder/volumes.py
- controller/src/controller/services/fileserver.py
- controller/src/controller/storage/kubernetes/creator.py
- controller/src/controller/storage/kubernetes/deleter.py
- controller/src/controller/storage/kubernetes/fileserver.py
- controller/src/controller/storage/kubernetes/lab.py
- controller/tests/data/extra-annotations/input/config.yaml
- controller/tests/data/fileserver/input/config.yaml
- controller/tests/data/fileserver/output/fileserver-objects.json
- controller/tests/data/homedir-schema/input/config.yaml
- controller/tests/data/standard/input/config.yaml
- controller/tests/data/standard/output/lab-objects.json
- controller/tests/handlers/files_test.py
- controller/tests/support/kubernetes.py
Previously, we were hoping to simplify the Kubernetes data model by combining volume specifications and their mount points into one data structure, under the assumption that each volume would only be mounted in one place.
Unfortunately, this broke for several reasons: we do have use cases where we want to mount the same volume on multiple paths, init containers must share volume definitions with the main container but do not share mounts, and file servers may eventually need the same volumes but different mounts. Separate the list of volumes and the list of mounts and tie them together with volume names, which are also used in constructing the Kubernetes objects.
This enables support for PVCs in init containers nearly for free; it just requires a bit of code in constructing the init …
> DM-41708: Separate volumes and volume mounts

- controller/src/controller/config.py
- controller/src/controller/constants.py
- controller/src/controller/services/fileserver.py
- controller/src/controller/services/lab.py
- controller/src/controller/services/prepuller.py
- controller/src/controller/storage/kubernetes/creator.py
- controller/src/controller/storage/kubernetes/custom.py
- controller/src/controller/storage/kubernetes/deleter.py
- controller/src/controller/storage/kubernetes/fileserver.py
- controller/src/controller/storage/kubernetes/ingress.py
- controller/src/controller/storage/kubernetes/lab.py
- controller/src/controller/storage/kubernetes/namespace.py
- controller/src/controller/storage/kubernetes/pod.py
- controller/src/controller/storage/kubernetes/watcher.py
- controller/src/controller/timeout.py
- controller/tests/services/lab_test.py
Add a new Timeout class that starts a timer when created and has methods to get the elapsed time, error message, and number of seconds left. Require a Timeout parameter to every Kubernetes storage layer function, and plumb that machinery all the way up to the service layer, using these Timeout objects for cumulative timeouts shared by a batch of operations. Operations that aren't part of a batch with their own configured timeout get a default timeout.
Add new configuration options for timeouts on deleting labs and file servers.
> DM-41793: Overhaul Kubernetes timeout handling (again)

- controller/src/controller/templates/fileserver.html.jinja
- controller/tests/data/fileserver/output/fileserver.html
Remove the clickable link to the user's file server at the top of the instructions, since the file server only supports WebDAV and following that link in a browser will not do anything useful.
Leave the link farther down after the instructions about how to access it in case people want to use copy link location.
> DM-41630: Remove clickable link to file server

- controller/src/controller/config.py
Make the default delete timeout for file servers match that for labs: one minute.
> DM-41793: Change default delete timeout for file servers

- controller/src/controller/dependencies/config.py
- controller/tests/handlers/files_test.py
- controller/tests/support/config.py
Test that Kubernetes errors during file server creation are caught properly and reported to Slack. This required some changes to the test setup to ensure that Slack webhook configuration is preserved when changing configurations.
> DM-41793: Add error handling tests for file servers

- controller/src/controller/config.py
- controller/src/controller/models/domain/kubernetes.py
- controller/src/controller/services/builder/fileserver.py
- controller/src/controller/services/builder/lab.py
- controller/tests/data/fileserver/input/config.yaml
- controller/tests/data/fileserver/output/fileserver-objects.json
- controller/tests/data/standard/input/config.yaml
- controller/tests/data/standard/output/lab-objects.json
- controller/tests/handlers/labs_test.py
Add support for configuring taint tolerations for file server and lab pods. Regenerate the lab objects for testing with the new Kubernetes object serialization function, which serializes everything with camel-case, matching the native Kubernetes syntax.
> DM-41820: Add tolerations to lab and file server pods

- controller/src/controller/config.py
- controller/src/controller/models/domain/kubernetes.py
- controller/src/controller/services/builder/fileserver.py
- controller/src/controller/services/builder/lab.py
- controller/tests/data/fileserver/input/config.yaml
- controller/tests/data/fileserver/output/fileserver-objects.json
- controller/tests/data/standard/input/config.yaml
- controller/tests/data/standard/output/lab-objects.json
Allow affinity rules to be specified for lab and file server pods. This unfortunately requires a whole Pydantic model for the (quite complicated) affinity models so that they can be parsed as part of the Nubaldo controller configuration.
> DM-41820: Add affinity support for labs and file server pods

- controller/src/controller/models/domain/kubernetes.py
- docs/_rst_epilog.rst
- docs/about/index.rst
- docs/admin/config/controller.rst
- docs/admin/config/fileserver.rst
- docs/admin/config/hub.rst
- docs/admin/config/images.rst
- docs/admin/config/index.rst
- docs/admin/config/lab.rst
- docs/admin/index.rst
- docs/dev/release.rst
Add a reference manual for Nublado configuration. Add more details to the release process, documenting how to update Phalanx for a new release.
Remove ReadWriteOnce from the list of supported modes for PVCs, since that access mode can never work with Nublado user labs or file servers.
> DM-38714: Document the Nublado configuration

- .gitignore
- authenticator/pyproject.toml
- authenticator/src/rubin/nublado/authenticator/_internals.py
- docs/admin/config/hub.rst
- docs/admin/index.rst
- docs/dev/api/authenticator.rst
- docs/dev/api/index.rst
- docs/dev/api/spawner.rst
- docs/dev/index.rst
- docs/documenteer.toml
- noxfile.py
- spawner/pyproject.toml
- spawner/src/rubin/nublado/spawner/__init__.py
- spawner/src/rubin/nublado/spawner/_internals.py
- spawner/tests/conftest.py
- spawner/tests/spawner_test.py
Add Python API documentation in the dev section for the JupyterHub plugins. Do a proofreading pass on that rendered documentation and clean up some cross-references.
Unfortunately, there doesn't seem to be a way to reference one package installed by Nublado from another package installed by Nublado in a way that Sphinx understands well enough to generate cross-references, so the mention of GafaelfawrAuthenticator in the NubladoSpawner documentation is not a link.
Rename RSPRestSpawner to NubladoSpawner to match the new naming convention, and define entry points per the JupyterHub documentation for the authenticator and the spawner.
Add missing documentation for the `jupyterhub.hub.baseUrl` configuration setting.
> DM-38714: Add internals documentation for JupyterHub plugins

- docs/dev/index.rst
The internal API documentation has a ton of objects and overwhelms the development page. Limit its depth, and the depth of the other categories to make the page a bit more readable.
> DM-38714: Limit link depth on developer page

- authenticator/pyproject.toml
- controller/src/controller/config.py
- controller/src/controller/factory.py
- controller/src/controller/services/builder/fileserver.py
- controller/tests/data/fileserver/input/config.yaml
- docs/admin/config/fileserver.rst
- docs/admin/config/lab.rst
- spawner/pyproject.toml
We don't want to make available via the file server every volume that is mounted in the lab container. Add an explicit volumeMounts configuration for the file server similar to the volumeMounts configuration for init containers, which allows us to pick and choose which volumes are mounted.
> DM-41979: Require explicit volume mounts for file servers

- .pre-commit-config.yaml
- controller/requirements/dev.txt
- controller/requirements/main.in
- controller/requirements/main.txt
- controller/tests/support/kubernetes.py
- hub/requirements/dev.txt
- spawner/src/rubin/nublado/spawner/_internals.py
Update to Safir 5.0.0, now that there is a full release supporting Pydantic v2. Update Ruff and let it change some formatting. Update Python dependencies generally.
> DM-41998: Update dependencies

- controller/src/controller/factory.py
- controller/src/controller/services/image.py
- controller/src/controller/storage/kubernetes/node.py
- controller/tests/data/gar-cycle/input/nodes.json
- controller/tests/data/prepuller/input/config.yaml
- controller/tests/data/prepuller/input/nodes.json
- controller/tests/data/prepuller/output/status.json
- controller/tests/data/standard/output/prepull-conflict-objects.json
- controller/tests/handlers/prepuller_test.py
- controller/tests/services/prepuller_test.py
- controller/tests/support/data.py
If nodeSelector is set for Nublado labs, apply the same node selector when choosing nodes that are eligible for prepulling. For node selector, just filter out the nodes from the prepuller status entirely rather than listing them but showing why they aren't eligible for prepulling. We'll use the latter strategy for tolerations, since tolerations are more temporary.
Use the new function for formatting Kubernetes objects for comparison purposes for the prepuller test objects.
> DM-42029: Add nodeSelector support to the prepuller

- controller/src/controller/factory.py
- controller/src/controller/models/domain/image.py
- controller/src/controller/models/domain/kubernetes.py
- controller/src/controller/services/image.py
- controller/src/controller/storage/kubernetes/node.py
- controller/tests/data/prepuller/input/config.yaml
- controller/tests/data/prepuller/input/nodes.json
- controller/tests/data/prepuller/output/status.json
- controller/tests/handlers/prepuller_test.py
- controller/tests/services/prepuller_test.py
- controller/tests/storage/kubernetes/node_test.py
- controller/tests/support/data.py
- docs/admin/config/images.rst
- docs/admin/config/lab.rst
If config.lab.tolerations are set, use them to select which nodes to which to prepull images. Report the nodes that are excluded by tolerations (but not the ones excluded by nodeSelector) in the prepull status as not eligible.
This required some restructuring of the data stored by the image service to retain more information about Kubernetes nodes.
> DM-42029: Add tolerations support to the prepuller

- controller/src/controller/background.py
- controller/src/controller/constants.py
- controller/src/controller/factory.py
- controller/src/controller/services/fileserver.py
- controller/src/controller/services/image.py
- controller/src/controller/services/lab.py
- controller/src/controller/services/prepuller.py
- controller/src/controller/storage/kubernetes/fileserver.py
- controller/tests/conftest.py
- controller/tests/services/prepuller_test.py
- docs/dev/api/controller.rst
Rather than each service having its own separate start and stop routines and background task scheduler, collect all background task management into its own BackgroundTaskManager. It handles the sequencing of running some operations on startup and then managing all of the tasks, and all of the service objects provide simple coroutine methods to do the work.
This will be used in later changes for cleaner invocation of work normally done in background tasks, avoiding delays and allowing easier testing of race conditions.
> DM-41907: Move background task management

- controller/tests/conftest.py
- controller/tests/handlers/files_test.py
- controller/tests/handlers/labs_test.py
- controller/tests/handlers/prepuller_test.py
- controller/tests/handlers/user_status_test.py
- controller/tests/models/domain/gafaelfawruserinfo_test.py
- controller/tests/services/lab_test.py
- controller/tests/services/prepuller_test.py
- controller/tests/support/data.py
In the controller test suite helper functions, automatically add .json to the file name passed to any read_*_json or write_*_json functions to save some typing and enforce consistency.
> DM-41907: Automatically add .json extension to test files

- controller/src/controller/background.py
When starting background tasks, we run the ones that should run during startup immediately. We therefore want to always delay by the interval before the first time we run the same task in the background or we unnecessarily run it twice quickly.
> DM-41907: Do not run background tasks immediately

- .github/workflows/ci.yaml
- .github/workflows/linkcheck.yaml
- .github/workflows/periodic-ci.yaml
Use the new `lsst-sqre/run-nox` composite GitHub Action to run nox, which arranges for caching of the nox virtual environments and hopefully will speed up GitHub Actions runs.
> DM-42119: Add nox environment caching

- controller/src/controller/services/builder/lab.py
- docs/admin/config/lab.rst
- docs/admin/home-directories.rst
- docs/admin/index.rst
- docs/admin/init-containers.rst
Write separate guides for choosing Nublado home directories and writing Nublado init containers, and move the NFS caution and the environment variable documentation there. Add documentation for the configuration settings for home directory paths, which I previously had missed.
Explicitly set the GID when spawning init containers as the user, not just the UID.
> DM-42125: Flesh out home directory and init container docs

- docs/dev/api/index.rst
- docs/dev/api/inithome.rst
- inithome/src/rubin/nublado/inithome/provisioner.py
Add the small rubin.nublado.inithome module to the generated internal API documentation.
> DM-42125: Add inithome to internals documentation

- controller/src/controller/services/builder/lab.py
- controller/tests/data/standard/input/config.yaml
- controller/tests/data/standard/output/lab-objects.json
Privileged init containers were being run as root but weren't being marked as privileged. This may be required to do some types of setup and was documented to be the case, and was being set with Nublado v3. Add that flag.
Add a test of a non-privileged init container and providing multiple init containers.
> DM-42153: Set privileged for privileged init containers

- controller/src/controller/services/builder/lab.py
- controller/tests/data/standard/output/lab-objects.json
Disable new privileges for user lab containers and drop all capabilities for user lab containers and init containers running as the user. Mark the root file system as read-only for all containers, even privileged containers, since we don't want to support dynamic modification of the root container.
> DM-42212: Add more security restrictions for labs

- controller/src/controller/services/builder/fileserver.py
- controller/tests/data/fileserver/output/fileserver-objects.json
File servers shouldn't need any cpaabilities, so configure them to drop all capabilities in their security context.
> DM-42212: Drop all capabilities in file server pods

- .github/workflows/ci.yaml
Only upload documentation for ticket branches if there were changes to the docs directory. Otherwise, just upload when tickets are merged into main.
> DM-42212: Upload fewer documentation changes

- docs/dev/release.rst
Note that one has to bump the version of the nublado-inithome container in all Phalanx values-*.yaml files.
> DM-42337: Add nublado-inithome to the release process

- changelog.d/20240102_161608_rra_DM_42337_queue.md
- controller/src/controller/handlers/files.py
- controller/src/controller/handlers/fileserver.py
- controller/src/controller/handlers/form.py
- controller/src/controller/handlers/index.py
- controller/src/controller/handlers/labs.py
- controller/src/controller/handlers/prepuller.py
- controller/src/controller/handlers/user_status.py
- controller/src/controller/main.py
Divide the routes into admin, hub, user, and internal tags and classify them according to required permissions.
> DM-42337: Classify routes with appropriate tags

- changelog.d/20240102_161405_rra_DM_42337_queue.md
- controller/src/controller/handlers/labs.py
- controller/src/controller/handlers/user_status.py
- controller/src/controller/models/v1/lab.py
- controller/src/controller/services/builder/lab.py
- controller/src/controller/services/lab.py
- controller/tests/data/standard/output/lab-status.json
- controller/tests/handlers/labs_test.py
- controller/tests/handlers/user_status_test.py
- controller/tests/models/v1/lab_test.py
- controller/tests/services/lab_test.py
The lab status routes were returning the full lab environment, which isn't desirable since the environment may contain secrets. They were also returning the complicated parameters we accept as input to specify the image, rather than clearly returning the image as chosen.
Fix this by splitting some of the models between input and output models and renaming them to avoid the word User for anything other than information about the actual user. The status now omits the environment and returns the full reference for the running image, rather than the complicated parameters passed in by the user.
This does mean we no longer have a good way of capturing the menu options that people are picking, but the right way to do that, should we ever care, is to add more logging.
Doing this removes the need …
> DM-42337: Rework the lab status models

- controller/src/controller/models/v1/lab.py
- controller/src/controller/services/builder/lab.py
The model renaming to separate input and output models broke some documentation cross-references.
> DM-42337: Fix broken documentation references

- controller/src/controller/main.py
redoc doesn't add a back link and neither does its Sphinx extension, so manually add one to the application description so that people browsing the documentation aren't stranded on the JSON API page.
> DM-42337: Add back link to REST API documentation

- controller/src/controller/handlers/labs.py
Override the FastAPI default of application/json and document in the OpenAPI schema that the events route returns text/event-stream.
> DM-42337: Document response type for event stream

- controller/src/controller/models/v1/prepuller.py
- controller/tests/data/prepuller/output/status.json
- controller/tests/data/standard/output/prepulls.json
See if this fixes some weird artifacts in the OpenAPI schema documentation. Change some list fields to always return lists and not support None for simplicity, where None and an empty list had the same meaning.
> DM-42337: Use Annotated types for prepuller models

- controller/src/controller/handlers/labs.py
Add a proper example in the OpenAPI schema for /spawner/v1/labs to make it clear that it returns a list of usernames.
> DM-42337: Add example for /spawner/v1/labs

- changelog.d/20240108_143023_rra_DM_42337.md
- docs/admin/config/images.rst
- docs/admin/gar.rst
- docs/admin/index.rst
- docs/admin/setup-gar.rst
Add documentation on how to set up Google Artifact Registry as an image source for Nublado, and on why this is the recommended configuration when Nublado is running on Google Kubernetes Engine.
> DM-42337: Add Google Artifact Registry documentation

- docs/admin/config/hub.rst
- docs/admin/delete-user-session.rst
- docs/admin/index.rst
- docs/admin/stop-all-labs.rst
- docs/admin/wipe-database.rst
Add admin procedures for deleting a user session, stopping all labs, and resetting the JupyterHub session database. Document the setting that tells JupyterHub to automatically update its database schema.
> DM-42337: Add additional upgrade and maintenance docs

- changelog.d/20240112_090145_rra_DM_42477.md
- docs/dev/plan.rst
The Helm chart in Phalanx now uses nublado-fileservers as the default Argo CD application and namespace, and now installs a NetworkPolicy to prevent unauthenticated connections to the file servers. Update the documentation accordingly.
> DM-42477: Update documentation for Helm chart fixes

- changelog.d/20240112_090145_rra_DM_42477.md
- changelog.d/20240112_101507_rra_DM_42477.md
- controller/src/controller/storage/kubernetes/watcher.py
Rather than special-casing the case where a resource version is specified, always retry Kubernetes watches on 410 errors, not just those with timeouts. Remove the delay before retrying the watch.
We were seeing this error every five minutes, admittedly in situations where the namespace was potentially being deleted, but it appears to be safe to immediately retry 410 errors.
> DM-42477: Always retry Kubernetes watches on 410 errors

- .github/workflows/periodic-ci.yaml
- noxfile.py
We need to update dependencies for the JupyterHub modules to do periodic CI testing of those modules, but we can't regenerate the dependencies of other components since they may require newer versions of Python. Add a new update-deps-hub session that can be used for that purpose.
> Fix periodic CI testing for JupyterHub modules

- controller/src/controller/services/lab.py
When waiting for lab deletion, all waiters updated the lab last modified date, which doesn't make sense. Only the one that does the actual state change should update the date.
> DM-42527: Remove spurious lab last modified update

- docs/admin/config/fileserver.rst
This was updated in 4.0.1 but the documentation wasn't updated accordingly.
> Fix name of Argo CD application for fileservers

- changelog.d/20240326_171124_rra_DM_43444.md
- controller/src/controller/handlers/fileserver.py
- controller/src/controller/models/v1/fileserver.py
- controller/src/controller/services/fileserver.py
- controller/tests/handlers/files_test.py
- docs/dev/api/controller.rst
As requested by the Portal team, add a new route for a user or a service acting on behalf of a user to get the status of their file server (/nublado/fileserver/v1/user-status). Return 404 if not running and 200 if running so that clients can ignore the body if they choose. (Currently there is no more-elaborate status to return.)
To maintain parallelism, add an admin .../v1/users/<username> route that returns the same information. Move the DELETE route for admin deletion of a file server under /users to align with the GET route that lists all users and to follow the normal REST URL pattern.
> DM-43444: Add more file server routes

- controller/src/controller/storage/kubernetes/node.py
The node information from Kubernetes apparently can have a None value for node.status.images[].names instead of a list. Catch that case and discard that image record, since we can't do anything with it.
> DM-45794: Catch another node image variation

- changelog.d/20240815_104721_rra_DM_45794.md
- noxfile.py
Reuse code in more places and remove duplicate logic. Reorder the init session and configure it to not use a virtualenv so that it will install uv before nox attempts to use it and not complain about the missing backend. Work around a bug in sphinxcontrib-redoc that prevented building the documentation twice. Avoid installing more than one editable module with the same uv command, since this seems to not work reliably. Remove a bunch of unnecessary installations of pip, setuptools, and wheel.
> DM-45794: Improve noxfile.py and fix some bugs

- controller/src/controller/handlers/fileserver.py
- controller/src/controller/timeout.py
- controller/tests/conftest.py
- controller/tests/handlers/labs_test.py
- controller/tests/services/prepuller_test.py
- pyproject.toml
- ruff-shared.toml
Adopt the shared Ruff configuration from the FastAPI Safir app template, with some changes that will be pushed upstream. Refactor some code that complained with the new Ruff configuration.
> DM-45794: Switch to a shared Ruff configuration

- changelog.d/20240815_164651_rra_DM_45794a.md
- controller/requirements/main.in
- controller/src/controller/config.py
All timeout configuration options now support the syntax parsed by Safir's `parse_timedelta` and therefore support human-friendly durations such as `6h` or `5m`.
> DM-45794: Support human-friendly timeout configuration

- CHANGELOG.md
Expand on the change log message for 7.0.0 to explain that the default changed.
> Better change log for 7.0.0

- authenticator/pyproject.toml
- controller/pyproject.toml
- inithome/pyproject.toml
- spawner/pyproject.toml
pytest-asyncio is changing the default for the asyncio fixture loop scope. Set it to the new default.
> Set default asyncio fixture loop scope

- .github/workflows/ci.yaml
Add trigger to Github CI for release action "published".
> Add trigger for published releases to Github CI

- .github/workflows/ci.yaml
- CHANGELOG.md
- changelog.d/20240924_172954_rra_naming.md
- docs/client/index.rst
After some more internal discussion, we decided to stick with the dash form. PyPI still seems to be using it, so change the places that used rubin.nublado.client back to rubin-nublado-client.
Clean up the change log for the 7.1.2 release somewhat.
> Revert module name back to dash form

- changelog.d/20241212_154123_rra_DM_48124a.md
- controller/src/controller/services/builder/fileserver.py
- controller/tests/data/fileserver/output/fileserver-objects.json
When creating `GafaelfawrIngress` resources for the file server, add a `service` configuration setting with value `nublado-files` for Gafaelfawr metrics reporting.
> DM-48124: Add service label to GafaelfawrIngress

- CHANGELOG.md
- changelog.d/20241212_154123_rra_DM_48124a.md
- changelog.d/20241212_162503_athornton_DM_48125.md
Collect change log for the 8.2.0 release and flesh out the change log entries for earlier releases.
> DM-48124: Prepare 8.2.0 release

- .github/dependabot.yml
Tell dependabot to check the Python dependencies of all of the components that are maintained like libraries so that it will relax major version pins where needed.
> Add pip dependabot configuration

- authenticator/src/rubin/nublado/authenticator/_internals.py
Add the `type` keyword to two type aliases in the authenticator now that we can assume Python 3.12 or later.
> DM-48216: Use type keyword when making type aliases

- .github/workflows/ci.yaml
Check the paths affected by the PR and do not build new JupyterLab base images unless the files that go into that image are affected. This will hopefully save some time in GitHub CI.
> DM-48216: Build fewer new JupyterLab base images

- client/src/rubin/nublado/client/nubladoclient.py
- controller/src/controller/storage/kubernetes/creator.py
- controller/src/controller/storage/kubernetes/deleter.py
- controller/src/controller/storage/kubernetes/ingress.py
- controller/src/controller/storage/kubernetes/pod.py
- controller/src/controller/storage/kubernetes/watcher.py
- spawner/src/rubin/nublado/spawner/_internals.py
Now that we can assume Python 3.12, use the new syntax for generics and eliminate uses of `Generic`, `TypeVar`, and `ParamSpec`.
> DM-48216: Use new Python 3.12 generics syntax

- .github/workflows/ci.yaml
- client/pyproject.toml
- client/src/rubin/nublado/client/nubladoclient.py
- client/tests/conftest.py
- docs/client/index.rst
Adjust the Nublado client for the new websockets 14.1 API. Fix the cache dependency for the client tests.
> DM-48216: Update to websockets 14.1

- client/src/rubin/nublado/client/exceptions.py
- client/src/rubin/nublado/client/models/_image.py
- controller/src/controller/exceptions.py
- controller/src/controller/models/domain/kubernetes.py
- controller/src/controller/services/source/docker.py
- controller/src/controller/services/source/gar.py
- controller/tests/support/gar.py
mypy now supports checking that methods marked as `@override` do indeed override a method in the parent class. Mark classes with override methods accordingly, since it provides some useful typo detection.
Unfortunately, the JupyterHub plugins cannot use this because for some reason mypy doesn't detect the methods on the parent class or JupyterHub doesn't declare them all.
> DM-48216: Add @override markers for overridden methods

- client/src/rubin/nublado/client/models/_image.py
- controller/src/controller/models/domain/kubernetes.py
- controller/src/controller/models/v1/lab.py
- spawner/src/rubin/nublado/spawner/_models.py
Rather than inheriting from `str, Enum`, use the `StrEnum` parent class, which does the same thing more thoroughly.
> DM-48216: Use StrEnum instead of dual inheritance

- changelog.d/20241220_115317_rra_DM_48216.md
- controller/src/controller/models/domain/gafaelfawr.py
- controller/src/controller/models/v1/lab.py
- controller/src/controller/services/builder/lab.py
- controller/tests/data/base/input/users.json
The Nublado controller no longer has to handle groups in the Gafaelfawr user information without GIDs, since Gafaelfawr dropped support for groups without GIDs in the 11.0.0 release.
> DM-48216: Drop support for groups without GIDs

- client/src/rubin/nublado/client/nubladoclient.py
- client/src/rubin/nublado/client/testing/_jupyter.py
- controller/src/controller/background.py
- controller/src/controller/services/fileserver.py
- controller/src/controller/services/lab.py
- controller/src/controller/timeout.py
- pyproject.toml
- spawner/tests/support/controller.py
Use `datetime.now(tz=UTC)` instead of `current_datetime` from Safir. The latter is now only useful when truncating times for database purposes. Python added the short `UTC` abbreviation, so the standard construction is more succinct and there's no reason to avoid it.
> DM-48216: Use standard Python way to get current time

- changelog.d/20250122_163137_rra.md
- controller/src/controller/exceptions.py
- controller/src/controller/handlers/form.py
- controller/src/controller/models/domain/gafaelfawr.py
- controller/src/controller/services/lab.py
- controller/src/controller/templates/unavailable.html.jinja
- controller/tests/data/base/input/users.json
- controller/tests/data/standard/output/lab-unavailable.html
- controller/tests/handlers/form_test.py
- controller/tests/handlers/labs_test.py
- controller/tests/support/gafaelfawr.py
Gafaelfawr now supports a flag in the user's notebook quota saying whether that user should be allowed to spawn a notebook. Implement support for that flag in the Nublado controller. If it is set to false, return an error message instead of a spawn form, and reject the actual spawn with a 403 error.
> DM-48546: Add support for blocking spawn with a quota flag

- client/pyproject.toml
- client/src/rubin/nublado/client/nubladoclient.py
- client/tests/client/client_test.py
- client/tests/mock/mock_test.py
- docs/client/index.rst
Python 3.13 adds a new warning when the `aclose` method of an async generator is not called explicitly. Async generators should ideally be explicitly shut down with `aclose` when they are no longer in use. Fix typing in some cases where async generators were returned but typed as async iterators (which don't require `aclose`), and close more generators explicitly. Include some async iterators from third party libraries that are actually generators, which requires working around the typing and some future-proofing for API changes.
Ignore the remaining warning that's internal to httpx-sse and can't be fixed at the client level.
> DM-48576: Suppress some client warnings for async generators

- changelog.d/20250124_115047_rra_DM_48576.md
- controller/src/controller/handlers/form.py
There were two possible reasons to not allow spawning in the spawner form: the `spawn` flag was set to false, or the user's quota did not allow any of the configured lab sizes. Merge those two cases into one check and use the same spawner error page for both.
> DM-48546: Merge handling of quota in spawner form

- changelog.d/20250131_164517_rra_DM_48696.md
- controller/src/controller/config.py
- controller/src/controller/events.py
- controller/src/controller/factory.py
- controller/src/controller/services/lab.py
- controller/tests/conftest.py
- controller/tests/handlers/labs_test.py
- controller/tests/services/lab_test.py
- docs/dev/api/controller.rst
- docs/documenteer.toml
Add metrics events for spawn successes, spawn failures, and the count of active, running labs. The spawn success and failure events include the username, Docker image reference, CPU limit, memory limit, and elapsed time. We may want to add more fields later.
The active lab count is logged via the background reconcile task.
> DM-48696: Add metrics events

- controller/src/controller/storage/kubernetes/node.py
If the Kubernetes control plane is overwhelmed, the Kubernetes API call to list nodes can time out. Rewrite that timeout error into the internal timeout exception so that it will be reported properly in Slack.
> DM-48760: Handle timeout exceptions when listing nodes

- changelog.d/20250124_163752_rra_DM_48597.md
- changelog.d/20250203_163705_rra_DM_48714.md
- controller/src/controller/services/lab.py
- controller/tests/handlers/labs_test.py
- controller/tests/handlers/user_status_test.py
- controller/tests/services/lab_test.py
Do not query Kubernetes for pod status when responding to status requests, and instead assume the internal state (which is reconciled periodically) is correct. The constant Kubernetes API requests for `Pod` status seemed to be overwhelming the control plane when there were a lot of pods running. Continue to ask Kubernetes directly immediately before spawn.
> DM-48714: Do not query Kubernetes for pod status

- changelog.d/20250203_172358_rra_DM_48761.md
- controller/src/controller/factory.py
- controller/src/controller/services/builder/prepuller.py
- controller/tests/data/standard/output/prepull-conflict-objects.json
- controller/tests/data/standard/output/prepull-objects.json
When Nublado was configured to add tolerations to lab pods, those tolerations were not also applied to prepuller pods. This meant that prepuller pods were never run if the node pool targeted by Nublado was tainted, such as when using a node pool restricted to only Nublado labs. Add the tolerations to prepuller pods as well.
> DM-48761: Add tolerations to prepuller pods

- changelog.d/20250207_131615_rra_DM_48838.md
- spawner/src/rubin/nublado/spawner/_internals.py
Remove the limit on the connection pool used to contact the Nublado controller from the JupyterHub spawner, since otherwise JupyterHub stops being able to do any work once the connections waiting for spawn progress exhaust the connect pool.
> DM-48838: Remove the spawner connection pool limit

- changelog.d/20250207_142337_rra_DM_48838.md
- controller/src/controller/factory.py
Remove the limit on the Kubernetes client connection pool in the Nublado controller. This will allow the controller to scale to more than 100 (the default) simultaneous watches.
> DM-48838: Remove Kubernetes connection pool limit

- changelog.d/20250207_153034_rra_DM_48838.md
- controller/src/controller/services/lab.py
The Nublado controller background reconciliation thread looks for labs that are no longer running and cleans up their resources. This loop was calling an async function in the middle of the loop over all labs, which meant that the dictionary over which it was looping could be changed by a different task in the middle of the loop. Instead, capture the current state first and loop over a snapshot of the lab to lab state mapping.
> DM-48838: Fix state tracking when deleting completed labs

- changelog.d/20250211_163247_rra_DM_48838.md
- controller/src/controller/factory.py
Relax the limit on the connection pool used to look up users in Gafaelfawr and query a Docker image repository.
> DM-48838: Remove HTTP client connection pool limit

- CHANGELOG.md
- Dockerfile.controller
- Dockerfile.inithome
- changelog.d/20250207_131615_rra_DM_48838.md
- changelog.d/20250207_142337_rra_DM_48838.md
- changelog.d/20250207_153034_rra_DM_48838.md
- changelog.d/20250211_112354_rra_DM_48838.md
- changelog.d/20250211_163247_rra_DM_48838.md
- controller/requirements/dev.txt
- controller/requirements/main.txt
- controller/src/controller/factory.py
Collect the change log for the 8.4.1 release. Update Python dependencies. Bump the minor version of Python used to construct the controller and inithome containers.
> DM-48838: Prepare 8.4.1 release

- docs/client/index.rst
- docs/index.rst
Fix the code example for mocking the client to use the correct mock for `websockets.connect`. Move the client documentation in the table of contents before the API and change log.
> DM-48977: Fix client testing documentation

- changelog.d/20250219_115241_danfuchs_DM_49032.md
- client/src/rubin/nublado/client/nubladoclient.py
- client/tests/conftest.py
Version 14 of `websockets` [changed the signature of the `connect` method](https://websockets.readthedocs.io/en/stable/howto/upgrade.html#extra-headers-additional-headers)
Without this, Mobu breaks with:
```
TypeError
create_connection() got an unexpected keyword argument 'extra_headers'
```
With this change, mobu is able to use the nublado client to execute notebooks again (tested locally).
> DM-49032: Fix another `websockets` >=14 breaking change

- changelog.d/20250224_201855_danfuchs.md
- client/pyproject.toml
The breaking change with Safir `10` is that Python 3.11 is no longer supported.
> Bump safir upper bound now that 10.0.0 is released

- client/src/rubin/nublado/client/nubladoclient.py
This is related to the Sentry error here:
https://rubin-observatory.sentry.io/issues/6323642042/?project=-1&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=4
Exception was raised in `DC2_catalog_access` notebook and the `run_python` method of `nubladoclient`, but output is not set in this case so we got an **UnboundLocalError**:
`cannot access local variable 'output' where it is not associated with a value`
Fix in PR is just to skip to next message when catching an Exception
> DM-49191: Skip to next message if Exception is raised in run_python

- client/src/rubin/nublado/client/nubladoclient.py
- client/tests/conftest.py
Add `ids` to the parameterized Nublado mock client fixture in the client tests for better test name reporting.
> DM-49493: Annotate the mock client fixture

- changelog.d/20250314_151626_rra_DM_49493.md
- controller/src/controller/services/builder/fileserver.py
- controller/tests/data/fileserver/output/fileserver-objects.json
Add `config.allowOptions` to the `GafaelfawrIngress` for file servers so that the server will work correctly with Gafaelfawr 13.0.0 and later.
> DM-49493: Set allowOptions in ingress for file server

- changelog.d/20250318_164842_rra_DM_49558.md
- controller/src/controller/services/builder/lab.py
- controller/tests/data/standard/output/lab-objects.json
The `NetworkPolicy` created for labs essentially did nothing: it tried to match JupyterHub or its proxy, which don't exist in the user namespace, and then created an ingress rule with no restrictions.
Fix the `NetworkPolicy` to behave as intended: Apply rules to the user lab and restrict access to only applications that are part of JupyterHub.
> DM-49558: Fix NetworkPolicy for user labs

- authenticator/src/rubin/nublado/authenticator/_internals.py
- changelog.d/20250321_115048_rra_DM_49624.md
In the JupyterHub authenticator, once the user logs out, we want to redirect them to the Gafaelfawr logout handler. This previously was done with a relative redirect to `/logout`. This fails with per-user subdomains, since this redirect may be to the JupyterHub hostname, which will then redirect back to the JupyterHub logout URL and create an infinite redirect loop. Add a configuration option to the authenticator that we can set in Phalanx to the URL of the Gafaelfawr logout route.
> DM-49624: Add configuration option for JupyterHub logout URL

- changelog.d/20250324_105714_rra_DM_49662.md
- controller/src/controller/services/lab.py
When cleaning up invalid labs found during state reconciliation, use the configured delete timeout instead of the Kubernetes request timeout.
> DM-49662: Use configured delete timeout for invalid labs

- changelog.d/20250324_174634_rra_DM_49662.md
- controller/src/controller/config.py
- controller/src/controller/services/builder/lab.py
- controller/tests/data/standard/input/config.yaml
- controller/tests/data/standard/output/lab-objects.json
Add a new Nublado controller setting (`lab.activityInterval`) that controls `JUPYTERHUB_ACTIVITY_INTERVAL` in the lab environment. This should be read by JupyterHub and used to configure how frequently user activity is reported back to JupyterHub.
> DM-49662: Support setting JUPYTERHUB_ACTIVITY_INTERVAL

- .github/workflows/ci.yaml
- changelog.d/20250326_162531_rra_DM_49735.md
uv now has built-in support for building and publishing PyPI packages, so drop the current composite action (which was using an old version of twine due to pinning an underlying action) and instead use uv directly.
Build the distribution and upload it in separate workflow jobs, following recommended best practices of doing as little as possible in the job with upload privileges.
> DM-49735: Use uv to build and upload PyPI packages

- authenticator/pyproject.toml
- controller/pyproject.toml
- inithome/pyproject.toml
- spawner/pyproject.toml
Some defense in depth against mistakes where we might upload packages that are not meant to be published on PyPI.
> DM-49735: Add do not upload markers to non-PyPI packages

- .github/workflows/ci.yaml
- .github/workflows/periodic-ci.yaml
Now that v3 of lsst-sqre/build-and-publish-to-pypi has been released, update the GitHub Actions workflows to reference it.
> DM-49735: Use released lsst-sqre/build-and-publish-to-pypi

- .github/workflows/ci.yaml
- changelog.d/20250328_150749_rra_DM_49774.md
GitHub is rate-limiting fetches of the inithome container during scaling tests. Also push it to Google so that we can hopefully get the benefit of a higher rate limit.
> DM-49774: Push inithome containers to Google

- changelog.d/20250624_162631_rra_DM_51529a.md
- controller/src/controller/background.py
- controller/src/controller/config.py
- controller/src/controller/constants.py
- controller/src/controller/factory.py
- controller/src/controller/models/v1/prepuller.py
- controller/tests/data/prepuller/output/status.json
- controller/tests/data/standard/output/prepulls.json
- controller/tests/handlers/files_test.py
- docs/admin/config/fileserver.rst
- docs/admin/config/images.rst
- docs/admin/config/lab.rst
Move the constants that controlled the refresh interval for image sources and node image caches and the reconcile intervals for file servers and labs into configuration options. This allows reducing the intervals when debugging and more easily overriding the intervals in the test suite.
> DM-51529: Add config options for refresh intervals

- changelog.d/20250625_151618_rra_DM_51556.md
- controller/src/controller/config.py
- controller/src/controller/handlers/form.py
- controller/src/controller/templates/spawner.html.jinja
- controller/tests/data/sizes/input/config.yaml
- controller/tests/data/sizes/output/lab-form.html
- controller/tests/handlers/form_test.py
- docs/admin/config/lab.rst
Add a new `controller.config.lab.defaultSize` configuration option that sets the default lab size explicitly. If it is not set, or is set to a size the user's quota does not allow them to spawn, the default remains the first-listed size that the user's quota allows them to spawn.
> DM-51556: Allow configuring the default lab size

- client/pyproject.toml
Safir 12.0.0 was just released, and is compatible with the Nublado client without any changes. Bump the max version so that apps that need Safir 12.0.0 and the client can resolve their deps.
> DM-52090: Bump safir max version

- changelog.d/20250917_155425_danfuchs_HEAD.md
- client/src/rubin/nublado/client/exceptions.py
Override the new `to_sentry` method on Slack exceptions:
https://safir.lsst.io/user-guide/sentry.html#special-sentry-exceptions
> DM-52391: client - Instrument exceptions with Sentry metadata

- controller/pyproject.toml
The `pyproject.toml` file for the Nublado controller defined an entry point pointing to a non-existent module. Remove it.
> DM-52784: Remove entry point for controller
