src/jupyterlabcontroller/models/domain/rsptag.py
tests/models/domain/rsptag_test.py

Analysis of available images and prepull state is very complex when expressed as operations on basic Python data types. In an attempt to divide that complexity into managable parts, introduce an abstract data type to collect RSPImageTags, return them in sorted order, filter them by cycle, and extract useful subsets of them.
The callers of this code will be added in subsequent changes. This is not ideal for review purposes, but the change that uses this data type is too large to be reviewable without extracting some preliminaries as separate changes. The supported operations here are only those needed by the subsequent change.

DM-37933: Add abstract data type collecting RSPImageTag

---

tests/configs/standard/input/config.yaml
tests/configs/standard/output/lab-objects.json

Use the same init container specification as IDF dev. Also sort the standard test configuration by key.

DM-38554: Add a test for init containers

---

src/jupyterlabcontroller/services/prepuller.py

We were already handling exceptions from creating pods, which was the most common prepuller error, but add a try/except block around the entire background thread and report any other uncaught exceptions to Slack. Pause for the image refresh interval after an uncaught exception.

DM-38554: Catch and report other prepuller errors

---

.github/workflows/ci.yaml
.github/workflows/linkcheck.yaml
docs/conf.py
docs/dev/index.rst
docs/dev/overview.rst
docs/documenteer.toml
docs/index.rst
tox.ini

This is currently just the build machinery for a manual and a not-very-great diagram of the internal code layout.

DM-38714: Add very basic manual build

---

src/jupyterlabcontroller/services/state.py
tests/services/state_test.py

If during lab reconciliation we discover a lab in pending status, we need to monitor it so that we see when it starts, just as if it were a lab we created. Otherwise, labs that were pending when the lab controller restarts will stay pending forever and never show as ready.

DM-38795: Handle pending labs found in reconciliation

---

src/jupyterlabcontroller/services/prepuller.py
src/jupyterlabcontroller/services/state.py
src/jupyterlabcontroller/storage/k8s.py
tests/handlers/labs_test.py
tests/services/prepuller_test.py
tests/services/state_test.py

Making this a pull request so that it will build an image. These changes will be reviewed separately.

Test patch queue branch

---

docs/dev/index.rst
docs/dev/plan.rst

This is a dump of my private to-do list and is probably not comprehensive. It includes a first-cut prioritization breaking things into four timescales.

DM-39383: Add upcoming development plan

---

docs/dev/plan.rst

Add some additional items, improve wording, and delete some things that have been resolved or turned out to not be an issue.

DM-39383: Add additional to-do items

---

src/jupyterlabcontroller/services/fileserver.py
src/jupyterlabcontroller/storage/k8s.py
src/jupyterlabcontroller/storage/kubernetes/custom.py
src/jupyterlabcontroller/storage/kubernetes/watcher.py

Add a new storage object for Kubernetes custom objects, and use it to generate a storage object for GafaelfawrIngress objects. Use that instead of direct calls to the custom object API.

DM-40691: Add a new-style CustomStorage class

---

src/jupyterlabcontroller/storage/k8s.py

When reconstructing file server state, we want to retrieve all jobs with a given label. Use a label selector so that Kubernetes does the work for us.

DM-40691: Use label selector for listing jobs

---

src/jupyterlabcontroller/services/lab.py

Move one of the private methods down to the private method section into its proper alphabetical spot.

DM-41051: Alphabetize LabManager methods

---

src/jupyterlabcontroller/services/lab.py
tests/handlers/labs_test.py

Previously, we returned 409 if someone attempted to delete a spawn that was still in progress. This interferes with cleanup that we want to do in the REST Spawner if JupyterHub was restarted while spawns are in progress. JupyterHub may lose the credentials for those labs and need to stop them so that they can be restarted with correct credentials, but the previous constraint meant that the stop would fail until the spawn completed.
Use the new cancel method on the monitor to stop any spawn in progress and then continue with a delete to clean up any remnant Kubernetes resources. Send a failure event to the event stream of any in-progress operation when the operation is cancelled.

Allow delete to abort an in-progress spawn

---

controller/src/controller/config.py
controller/src/controller/dependencies/config.py
controller/src/controller/dependencies/context.py
controller/src/controller/handlers/fileserver.py
controller/src/controller/handlers/labs.py
controller/src/controller/models/domain/form.py
controller/src/controller/models/domain/gafaelfawr.py
controller/src/controller/models/domain/kubernetes.py
controller/src/controller/models/domain/rsptag.py
controller/src/controller/models/v1/lab.py
controller/src/controller/models/v1/prepuller.py
controller/src/controller/services/form.py
controller/src/controller/services/image.py
controller/src/controller/services/lab.py
controller/src/controller/services/size.py
controller/src/controller/storage/kubernetes/lab.py
controller/src/controller/storage/kubernetes/pod.py
controller/src/controller/storage/kubernetes/watcher.py
controller/src/controller/util.py
controller/tests/models/domain/gafaelfawruserinfo_test.py
noxfile.py
pyproject.toml

Remove all the temporary Ruff exclusions and fix the remaining issues. This was mostly docstring cleanup, but also required refactoring a couple of methods that were too complex.

DM-41595: Fix remaining Ruff issues

---

controller/src/controller/services/fileserver.py

If an exception is raised while watching for completed file server pods, log it, wait a second, and restart the watch rather than letting the thread exit and thus silently stopping watching for completed pods.

DM-41622: Recover after exceptions in file server watcher

---

controller/src/controller/services/fileserver.py

Wrap the overall file server creation in an explicit timeout in addition to the timeouts passed into lower-level operations, and handle that exception explicitly with appropriate logging.

DM-41622: Add explicit timeout for creating file servers

---

controller/src/controller/handlers/fileserver.py
controller/src/controller/services/fileserver.py
controller/tests/handlers/fileserver_test.py

Rather than raising the exception from a failed file server creation or deletion, translate the exception into a proper HTTP 500 error with information from the underlying exception.
Raise richer TimeoutError exceptions that include the operation and the elapsed time.

DM-41622: Properly handle file server exceptions

---

controller/src/controller/dependencies/context.py
controller/src/controller/dependencies/user.py
controller/src/controller/handlers/fileserver.py
controller/src/controller/handlers/form.py
controller/src/controller/handlers/index.py
controller/src/controller/handlers/labs.py
controller/src/controller/handlers/prepuller.py
controller/src/controller/handlers/user_status.py
controller/src/controller/storage/gafaelfawr.py

Switch all FastAPI handlers to use the new Annotated syntax. Add a new FastAPI dependency to get the username from the path and also from X-Auth-Request-User and ensure that they match.

DM-41630: Update FastAPI handler parameters

---

controller/src/controller/models/v1/prepuller.py
controller/src/controller/services/image.py

Move more of the data conversion into the model instead of the service.

DM-41630: Add method to create NodeImage from RSPImage

---

controller/src/controller/services/fileserver.py
controller/src/controller/services/lab.py
controller/src/controller/services/prepuller.py

Previously, exceptions while spawning labs, file servers, and prepuller pods were reported to Slack, but timeouts were not, which in practice may be hiding timeout problems from us. Add Slack reporting of unexpected timeouts in all three places.

DM-41630: Report timeouts to Slack

---

noxfile.py

Replicate the support in the non-monorepo Makefile system for building a version of the dependencies without hashes so that we can test against unreleased dependencies, such as a branch of Safir.

DM-41630: Add support for update-deps-no-hashes

---

controller/src/controller/services/fileserver.py

The file server reconciliation was not correctly handling the new state tracking where every user continues to have a record, and there were some possible race conditions in the cleanup. Restructure it to hopefully avoid those issues.

DM-41708: Fix file server reconciliation bugs

---

controller/src/controller/exceptions.py
controller/src/controller/services/fileserver.py
controller/src/controller/services/lab.py
controller/src/controller/services/prepuller.py
controller/src/controller/storage/kubernetes/custom.py
controller/src/controller/storage/kubernetes/deleter.py
controller/src/controller/storage/kubernetes/namespace.py
controller/src/controller/storage/kubernetes/pod.py
controller/src/controller/timeout.py
controller/tests/services/lab_test.py

Add a ControllerTimeoutError exception that is similar to TimeoutError but with a better message and with support for posting to Slack. Have the Timeout class take over calling asyncio.timeout, and add support to it for translating the exception to ControllerTimeoutError and adding the additional exception metadata.
This allows removal of the error method on timeouts, since they now handle their own exception creation.

DM-41793: Add separate exception for timeouts

---

controller/src/controller/config.py
controller/src/controller/services/builder/fileserver.py
controller/src/controller/services/builder/lab.py
controller/tests/data/fileserver/input/config.yaml
controller/tests/data/fileserver/output/fileserver-objects.json
controller/tests/data/standard/input/config.yaml
controller/tests/data/standard/output/lab-objects.json

Add support for specifying nodeSelector labels to both labs and file servers.

DM-41820: Add nodeSelector for labs and file servers

---

docs/dev/development.rst
docs/dev/plan.rst

Go through the development plan and remove tasks that have been completed. Tweak the development documentation a little bit.

DM-38714: Remove completed development tasks

---

docs/about/index.rst
docs/index.rst

- Redo how top-level sections are handled on the main page
- Add more structure to the component diagrams

DM-38714: Documentation formatting cleanups

---

controller/src/controller/services/lab.py

Include the username in a few more log messages. Log cancellation of operations, and use cancelled instead of aborted as slightly better terminology. Log when we start monitoring a spawn in progress due to background reconciliation.

DM-41907: Improve logging of lab operations

---

authenticator/pyproject.toml
docs/about/fileserver-create.mmd
docs/about/index.rst
docs/about/lab-spawn.mmd
docs/conf.py
spawner/pyproject.toml

Add Mermaid sequence diagrams for lab spawning and file server creation based on the diagrams in SQR-066.

DM-38714: Add sequence diagrams to documentation

---

controller/src/controller/services/builder/fileserver.py
controller/tests/data/fileserver/output/fileserver-objects.json

Use the new per-user ingress feature of Gafaelfawr to restrict access to the ingress for a user file server to only the user that spawned that file server.

DM-41998: Restrict access to file server ingress

---

controller/src/controller/templates/spawner.html.jinja
controller/tests/data/standard/output/lab-form.html

Our boxes, they did nothing.  NOTHING.

tickets/DM-42070: Set checkbox value to true in spawner form

---

controller/src/controller/services/fileserver.py
controller/src/controller/services/lab.py

Both labs and file servers had race conditions with background reconcile where reconcile might try to retrieve data while a spawn was in progress, see an incomplete configuration, and decide to delete the objects. The previous care with which the reoncile method was written was not sufficient to avoid this.
To try to address this problem, add last modified timestamps to the internal state that are updated whenever the lab or file server is changed (created or deleted), and check those timestamps as well as whether an operation is in progress when doing reconciliation. If the state has changed since the collection of data for reconciliation started, leave it alone and wait for the next pass.

DM-41907: Fix race conditions for labs and file servers

---

controller/src/controller/background.py

In the BackgroundTaskManager, the method for calling a service method in a loop was incorrectly trying to reuse a coroutine instead of starting from the method and calling it repeatedly to create new coroutines. Fix the syntax and typing.

DM-41907: Fix syntax for starting background tasks

---

docs/about/fileserver-create.mmd
docs/about/lab-spawn.mmd
docs/conf.py

Require the current version of Mermaid so that we can use actor creation and restructure the Mermaid diagrams a bit to be clearer.

DM-42337: Tweak the Mermaid interaction diagrams

---

docs/dev/controller.rst
docs/dev/plan.rst

- Improve the controller architecture diagram by adding the background service
- Update the development plan

DM-42337: Further documentation improvements

---

docs/admin/config/index.rst

Phalanx documentation has been restructured.

Fix broken link

---

changelog.d/20240605_102630_athornton_DM_44689.md
changelog.d/20240606_102104_athornton_DM_44689.md
controller/src/controller/config.py
controller/src/controller/services/builder/prepuller.py
controller/src/controller/templates/spawner.html.jinja
controller/tests/data/standard/output/lab-form.html
controller/tests/data/standard/output/prepull-conflict-objects.json
controller/tests/data/standard/output/prepull-objects.json

Add limits and requests to prepulled pods.

tickets/DM-44689: Add resource limits/requests to prepulled pods

---

changelog.d/20240613_085608_athornton_DM_44731.md
controller/src/controller/config.py
controller/src/controller/constants.py
controller/src/controller/services/builder/lab.py
controller/tests/data/changed-path/input/config.yaml
controller/tests/data/standard/input/config.yaml
controller/tests/data/standard/output/lab-objects.json
controller/tests/handlers/labs_test.py

Make command and directory root customizable in order to accommodate changes for two-Python Lab container.

tickets/DM-44731: make command and directory root customizable

---

CHANGELOG.md

Add missing version numbers and anchors and reword the change log messages for consistency with other entries.

DM-45132: Fix change log entries for recent releases

---

.github/workflows/periodic-ci.yaml

The keyword for if is failure, not failed.

DM-45794: Fix error in periodic CI configuration

---

CHANGELOG.md

Expand on the change log entries to provide a bit more detail.

Flesh out the change log for 7.2.0

---

CHANGELOG.md

Try to provide a more helpful change log that describes the impact on the user rather than terse descriptions of the code change.

Rewrite change log for 8.0.0

---

client/src/rubin/nublado/client/exceptions.py
client/tests/exceptions/sanitize_body_test.py
client/tests/exceptions/sanitize_slack_test.py
client/tests/exceptions/sanitize_url_test.py

This should make JupyterWebError formatting less grotesque.

Correct some Slack formatting

---

CHANGELOG.md
changelog.d/20250318_164842_rra_DM_49558.md
controller/requirements/dev.txt
controller/requirements/main.txt

Collect change log for the 8.7.1 release and update Python dependencies.

DM-49558: Prepare 8.7.1 release

---

.github/workflows/periodic-ci.yaml

Add a packaging test for PyPI to the periodic CI GitHub Actions workflow.

DM-49735: Add periodic PyPI packaging test

---

CHANGELOG.md
Dockerfile.jupyterlab-base
changelog.d/20250130_125621_athornton_DM_47346.md
changelog.d/20250328_150749_rra_DM_49774.md
jupyterlab-base/scripts/install-jupyterlab

Picks up query extension work and newer released jupyter-server

tickets/DM-47346: rebuild jupyterlab-base

---

Dockerfile.controller
Dockerfile.fsadmin
Dockerfile.inithome
Dockerfile.jupyterhub
Dockerfile.purger
Makefile
scripts/update-uv-version.sh

Copy over the script that updates pinned uv versions and update older versions in various Dockerfiles.

DM-52657: Update pinned uv versions during make update
